### ISSUE TITLE
pager

### ISSUE THREAD

**Issue by davekaufman** [charmbracelet/glow#109]
As implemented, `glow` lacks an inbuilt pager, and piping to an external pager like `less` or `bat` removes highlighting.

**Comment by muesli** [comment]
glow detects not printing to a terminal and disables the default styling. You can however enforce it:

```bash
glow -s dark | less -r
```

**Comment by davekaufman** [comment]
Duly noted, with my thanks.

I will note that this behavior seems inconsistent to me.
I would argue that a separate flag should enable sending of control chars through the pipe - either that, or turn off styling by default - either would result in more predictable behavior. 

Either way, cool utility, thanks for making it.

**Comment by SleeplessSloth** [comment]
You could automatically use the pager from `$PAGER` (or `less` by default) if the content doesn't fit on the screen. A-la how `systemctl` or `git log` work. And maybe even a flag to force pager off? Again, just like `git --no-pager log`

**Comment by djsnipa1** [comment]
Just wanted to chime in...glow works great like this:

add this to your `~/.bashrc`, `~/.zshrc`, or `~/.aliases` file:

```
# view .md files in terminal with glow
mdless() {
    glow "$@" -s dark | less -r
}
```

Then when you close and re-open your terminal, just type 

```
mdless README.md
```
or whatever filename you want to be paged.

**Comment by muesli** [comment]
I've added the `-p` flag to glow, which automatically pipes the output to your `$PAGER` (or `less -r` if that's not set).
