### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by dikiaap** [charmbracelet/glow#112]
Hi, thanks for making this cool CLI app. The current dark theme doesn't suit with my terminal color scheme. Adding a feature to support customized color scheme would be nice. Maybe with parameter like [fzf](https://github.com/junegunn/fzf/wiki/Color-schemes), or config file like [alacritty](http://github.com/jwilm/alacritty/blob/v0.4.0/alacritty.yml#L185-L251), or .sublime-syntax file like [bat](https://github.com/sharkdp/bat/blob/v0.12.1/README.md#adding-new-syntaxes--language-definitions).

Related: #114

**Comment by muesli** [comment]
You can already do that! Check out https://github.com/charmbracelet/glamour/tree/master/styles to see how you can write your own style definitions, as well as the current settings of the dark & light styles (`dark.json` and `light.json`).

**Comment by dikiaap** [comment]
Thanks for the quick response. Is there any specific location to store this file instead of calling it many times?

**Comment by muesli** [comment]
Currently you have to pass the style to glow like this: `glow -s mystyle.json`.

We'll think about adding an optional config file and default search paths.

**Comment by Sigafoos** [comment]
I ran into this just now as it isn't picking up on what `auto` should resolve into (which could be something weird with my setup). My use case needs just the path to the command to execute and no flags, so I can't set it to `glow -s dark`.

**Comment by muesli** [comment]
Good news everyone, glow now supports a config file! See README for more information!
