### ISSUE TITLE
`glow-bin` on arch linux

### ISSUE THREAD

**Issue by GaugeK** [charmbracelet/glow#113]
Would it be possible to get a glow-bin AUR package? It's annoying installing go every time I want to build a go package from the AUR, especially since go is quite large.

**Comment by muesli** [comment]
Sure, we'll add `glow-bin`!

**Comment by GaugeK** [comment]
Thank you.

**Comment by muesli** [comment]
Added to AUR: https://aur.archlinux.org/packages/glow-bin/
