### ISSUE TITLE
Extraneous spaces?

### ISSUE THREAD

**Issue by crides** [charmbracelet/glow#115]
When using `glow` to render markdowns, it seems like there are a lot of useless spaces at the end of lines. You can see in this screenshot (run with `glow github.com/charmbracelet/glow | bat -A`, where the blue dots are spaces):

![maim-2019-12-23--14-35-38](https://user-images.githubusercontent.com/15631555/71379616-91832c80-2591-11ea-9d86-ba097748168e.png)

**Comment by muesli** [comment]
I've moved this issue to `glow`, as I don't consider it a bug in the context of `glamour`. Here the padding indeed is an intended feature.

However, I can understand why in the context of `glow` this might not be the desired effect, *if* the padding itself isn't styled - for example when background colors are being applied.

I've therefore fixed this in glow itself and we now trim un-styled spaces from the end of each line.
