### ISSUE TITLE
Installing with go get fails with `undefined: aurora.Reset` in glamour

### ISSUE THREAD

**Issue by MickaelBergem** [charmbracelet/glow#117]
I'm trying to install glow through `go get`:

```
$ go get github.com/charmbracelet/glow
# github.com/charmbracelet/glamour/ansi
/data/go/src/github.com/charmbracelet/glamour/ansi/baseelement.go:99:9: undefined: aurora.Reset
```

My go version:

```
$ go version
go version go1.12.12 linux/amd64
```

**Comment by muesli** [comment]
Sounds like you got an older version of `aurora` lingering around in your `GOPATH`.

Either try updating the dependencies with `go get -u github.com/charmbracelet/glow` or force using Go modules:

```
GO111MODULE=on go get github.com/charmbracelet/glow
```

Closing for now, but please don't hesitate reporting back should you still run into issues! Thank you!

**Comment by MickaelBergem** [comment]
Ah! My bad, sorry about this. Your suggestion worked perfectly - I'm not yet used to Go dependency management and assumed it worked the same way as other languages, where a specific version of each dependency is installed.

Thanks!

**Comment by muesli** [comment]
Glad that helped! Btw, when you use Go modules (either by using the env-var I mentioned or upgrading to Go 1.13) exactly that happens: each dependency is pinned to a specific version.
