### ISSUE TITLE
Detect terminal's width and limit default word-wrap setting to it

### ISSUE THREAD

**Issue by lofic** [charmbracelet/glow#122]
I am subjected to a scrolling problem.

Immediately after : 

glow -p mydoc.md

the head (first lines/pages) of the document is missing.

I can't scroll up to the head.

But if I scroll down, then up, I can get to the head, with missing characters at the start of the lines

See screenshot in attachment (glow left, bat right)

![glow_vs_bat](https://user-images.githubusercontent.com/692300/71766721-24618680-2f03-11ea-9577-eaa81f17bfa9.png)

**Comment by muesli** [comment]
I'm afraid I can't reproduce that. Which pager command are you using?

**Comment by lofic** [comment]
Hello, here is a file to reproduce (try to display it with in a terminal with only a few lines in height) :

```
+++
weight = 20
+++

## Lorem

```bash
alias glow='glow -s light'
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


## Ipsum


Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Dolor

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```

I tested it in gnome terminal and terminator.

The command line is :

glow -s light -p thedoc.md

Without the -p flag the content is displayed as expected.

**Comment by muesli** [comment]
Ok, I can reproduce that if the terminal is narrower than the output width. I assume this is a problem in less, as it's not really aware of ANSI escape sequences.

You can work-around it by specifying a different width:

```
glow -w 60 ...
```

In the longterm, we should probably detect the current terminal's width and adjust the reflow settings accordingly.

**Comment by j-james** [comment]
I'm encountering this / a similar issue without a pager.

![2020-04-10-015843](https://user-images.githubusercontent.com/35242550/78978944-ac8d9400-7acf-11ea-9011-db94f75b0b0d.png)
![2020-04-10-015857](https://user-images.githubusercontent.com/35242550/78978947-ae575780-7acf-11ea-9cd6-25560a36330f.png)

(the last image is `glow` ran after resizing the terminal)

Specifying a width fixes it, but +1 for a longterm solution.

**Comment by muesli** [comment]
Thanks for your patience, this should be fixed in the latest release!

**Comment by jpmvferreira** [comment]
As a solution for this problem been provided? By default the configuration file sets the width at 80 and there seems to be no auto configuration setting, which if there is, I believe it should be the default.

**Comment by adastx** [comment]
Any update?

**Comment by miaLDN** [comment]
Even BASH knows the terminal size.

Glow is not detecting the terminal width??

```bash
$ echo "$COLUMNS ✕ $LINES"
73 ✕ 41
```
