### ISSUE TITLE
Include example.jpg text as markdown for testing

### ISSUE THREAD

**Issue by moderation** [charmbracelet/glow#130]
As per https://twitter.com/moderat10n/status/1209137416700719106 it would be nice to include example.md containing the text in the PNG file. This would allow comparison and reference testing.

**Comment by meowgorithm** [comment]
Hi! This can be found in the [Glamour](https://github.com/charmbracelet/glamour/) library:

https://github.com/charmbracelet/glamour/blob/master/testdata/example.md
