### ISSUE TITLE
Add Line Numbers

### ISSUE THREAD

**Issue by thomasharmon808** [charmbracelet/glow#131]
Bat has this feature and it's really useful. Would it be possible to add line numbers with the output similar to bat?

**Comment by muesli** [comment]
I agree it's nice, but I don't think we need to implement that feature into glow itself, you can already do that:

```
glow -s dark | cat -n
```

**Comment by thomasharmon808** [comment]
Didn't even think of that, that's awesome! Thanks :D

**Comment by moderation** [comment]
`glow -s dark | bat` gives you line numbers and paging.
