### ISSUE TITLE
Make it aware of lowercase readme by default

### ISSUE THREAD

**Issue by StreetStrider** [charmbracelet/glow#134]
Make runner aware of `readme.md` as well. Some people prefer all files to be lowercased, including readme. Now it's required to pass such name explicitly, wasting time.

**Comment by muesli** [comment]
Good point, I'll make the search list case-insensitive.

**Comment by muesli** [comment]
Fixed by c5517ad.

**Comment by StreetStrider** [comment]
Thank you for your efforts.

**Comment by StreetStrider** [comment]
Hello. This isn't working in v1.1.0. I see some intro page when running without arguments.
Was this feature dropped or it's just a flaw?
Also, the intro page doesn't mention local readme file if it is lowercased.

**Comment by muesli** [comment]
Starting Glow v1+ without any arguments will launch a TUI mode which should list all markdown files it can find in the current working dir (and below). Is this not working for you?

**Comment by StreetStrider** [comment]
I understand. I've been using it when it opens readme by default. So this behavor has been changed with major release, OK.
