### ISSUE TITLE
Color theme in `example.png`

### ISSUE THREAD

**Issue by jakobhellermann** [charmbracelet/glow#137]
I really like the color theme in the [example.png](https://raw.githubusercontent.com/charmbracelet/glow/master/example.png) , but I could not find it searching online.
What's its name?

**Comment by muesli** [comment]
We made it ourselves. It's glamour's dark style and you can find the definitions here:

https://github.com/charmbracelet/glamour/blob/master/styles.go

**Comment by jakobhellermann** [comment]
okay, thanks
