### ISSUE TITLE
Unable to build glow on macOS

### ISSUE THREAD

**Issue by mikemadden42** [charmbracelet/glow#138]
```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
```

```bash
$ go version
go version go1.13.7 darwin/amd64
```

I'm getting this error when I build glow on macOS:

```bash
$ go get -u -ldflags "-s -w" github.com/charmbracelet/glow
# github.com/charmbracelet/glamour/ansi
go/src/github.com/charmbracelet/glamour/ansi/codeblock.go:110:3: unknown field 'Forward' in struct literal of type indent.Writer
go/src/github.com/charmbracelet/glamour/ansi/heading.go:70:3: unknown field 'Forward' in struct literal of type indent.Writer
go/src/github.com/charmbracelet/glamour/ansi/margin.go:37:3: unknown field 'Forward' in struct literal of type padding.Writer
go/src/github.com/charmbracelet/glamour/ansi/margin.go:51:3: unknown field 'Forward' in struct literal of type indent.Writer
go/src/github.com/charmbracelet/glamour/ansi/table.go:51:3: unknown field 'Forward' in struct literal of type indent.Writer
```

**Comment by muesli** [comment]
This is a temporary issue while I'm currently updating `glamour` & `reflow`, two dependencies of glow. Please simply clone this repository, `cd` to it and run `go build` inside it. This will use the pinned dependencies and should work fine. We should probably update the README accordingly.

**Comment by bAndie91** [comment]
hi, it won't build on linux either.

go version go1.10.3 linux/386

glow: commit fdaa2ca
glamour: tested with both commit 7467d9e (pinned in go.mod) and 66b7555 (latest) too.

**Comment by muesli** [comment]
I'm afraid Go 1.10 doesn't support modules yet. So you would have to make sure _all_ of glow's and glamour's dependencies are checked out to the pinned version within your `$GOPATH`.

**Comment by bAndie91** [comment]
ok, I managed to build glow by setting transitive dependency 'reflow' to e5efeac as indicated in glamour's go.mod. i wonder why `go get` has checked the master branches out rather than the pinned versions.

**Comment by muesli** [comment]
That's because Go 1.10 doesn't support modules. It will _always_ check out git master of all dependencies.

**Comment by bAndie91** [comment]
@muesli thanks, yes, my go version must be the tricker.

**Comment by muesli** [comment]
I've updated `glamour` and `reflow`, so everything should be building with or without Go modules again - for now: upstream dependencies may always break API compatibility, which is why we genereally advise to use Go 1.11+ and the pinned module deps.

Thanks for all your feedback, closing this one now :smiley:
