### ISSUE TITLE
Why showing # in headers ?

### ISSUE THREAD

**Issue by pascalandy** [charmbracelet/glow#139]
Hi,

For H1 we don't see `#`:) But for H2, H3 we can see `#` :(
Why is that? Any option to see a normal formatting instead?

### Screenshot

![Screen Shot 2020-02-08 at 6 38 37 PM](https://user-images.githubusercontent.com/6694151/74093617-7b2e2300-4aa2-11ea-92d8-643d4b8b4d12.jpg)

Thanks :)

**Comment by muesli** [comment]
You could edit your own style JSON and tweak it! Check out the documentation and style definitions at https://github.com/charmbracelet/glamour/tree/master/styles

**Comment by pascalandy** [comment]
thanks!

REF: https://github.com/charmbracelet/glamour/tree/master/styles#h1---h6
