### ISSUE TITLE
glow doesn't use WithAutoPrefix

### ISSUE THREAD

**Issue by Sigafoos** [charmbracelet/glow#144]
The change made in charmbracelet/glamour#64 introduced the `WithAutoStyle()` method, but that isn't used here. As a result, if you don't pass an explicit style name it will use `auto`, which [isn't a default style](https://github.com/charmbracelet/glamour/blob/master/styles.go#L649-L655) and throws an error. With a fresh install via `go get`:

```
> glow README.md
Error: auto: style not found
Usage:
  glow SOURCE [flags]

Flags:
  -h, --help           help for glow
  -p, --pager          display with pager
  -s, --style string   style name or JSON path (default "auto")
  -v, --version        version for glow
  -w, --width uint     word-wrap at width (default 100)
```

**Comment by muesli** [comment]
This should only affect you if you're building _without_ Go modules, which isn't recommended for that very reason: it will pull the latest HEAD of every dependency instead of the pinned versions.

That being said, I'm about to upgrade `glow` to make use of the latest upstream changes.

**Comment by muesli** [comment]
Bumped dependencies on master. `glow` now uses `glamour`'s `WithAutoStyle()`.

**Comment by Sigafoos** [comment]
Oh, strange! It was on a fresh install of go 1.14 (new laptop), which I thought no longer needed to explicitly turn module support on, but either way seems to have been a PEBKAC issue. Thanks for the quick response!

**Comment by muesli** [comment]
@Sigafoos That's odd indeed. I assume that also means you didn't set `GO111MODULE` to any particular value?
