### ISSUE TITLE
bash code syntax highlighting not displaying correctly

### ISSUE THREAD

**Issue by jonnyhoff** [charmbracelet/glow#149]
OS: Fedora 32

Output:
![image](https://user-images.githubusercontent.com/8642945/86900270-674b2380-c10b-11ea-9019-66ee52046604.png)

Markdown file:
![image](https://user-images.githubusercontent.com/8642945/86900088-2eab4a00-c10b-11ea-8e6e-91b7c9f71242.png)

**Comment by meowgorithm** [comment]
Try `console` instead of `bash`.

**Comment by toolleeo** [comment]
I have the same problem with glow 0.2.0. But not only for bash code: it happens to code blocks of any language.
This does not happen for inline code.

I checked previous stable versions of glow from the releases, and the problem seems to be present also for 0.1.6 and 0.1.5.

**Comment by muesli** [comment]
Sorry about that, investigating!

**Comment by muesli** [comment]
I'm afraid I can't reproduce that at all. Which terminal are you using? Can you do me favour and paste the entire markdown either here or in a pastebin? Thank you!

**Comment by muesli** [comment]
We've upgraded our syntax highlighter `chroma` to the latest stable release. Since we can't reproduce the issue, we'll need a bit more information. Can you try it with the latest release of glow? Closing this for now, assuming it has been fixed upstream.
