### ISSUE TITLE
Problem with GLIBC_2.32 on Ubuntu 19.10

### ISSUE THREAD

**Issue by apiraino** [charmbracelet/glow#161]
Hi,

I tried installing the file `glow_1.0.0_linux_amd64.deb`, but:

```
$ sudo dpkg -i glow_1.0.0_linux_amd64.deb 
Selecting previously unselected package glow.
(Reading database ... 297288 files and directories currently installed.)
Preparing to unpack glow_1.0.0_linux_amd64.deb ...
Unpacking glow (1.0.0) ...
Setting up glow (1.0.0) ...

$ glow --version
glow: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by glow)
```

As of today latest version on Ubuntu 19.10 is `2.30-0ubuntu2.2`

(`glow` v0.2.0 worked fine)

**Comment by muesli** [comment]
We've just pushed a v1.0.1 which should fix this issue. Thanks for bringing this to our attention!

**Comment by apiraino** [comment]
Christian Muehlhaeuser writes:

> We've just pushed a v1.0.1 which should fix this issue. Thanks for bringing this to our attention!

Thanks for the superquick fix!
