### ISSUE TITLE
Requires go 1.13

### ISSUE THREAD

**Issue by trini** [charmbracelet/glow#164]
Installing on Ubuntu 18.04, which provides go 1.10.4 gives the error:
```
package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)
```
which after some quick searching means that you need to have go 1.13 for that particular line to work.

**Comment by muesli** [comment]
I'm afraid that's correct. Two options here:

1. You can use a package/binary from the releases page
2. It's really straightforward to install a newer Go on older distros.

We'll clarify that Go 1.13+ is a requirement in the README.

**Comment by trini** [comment]
Sounds good to me, thanks!
