### ISSUE TITLE
Glow tui help menu displays 'j/↓ down' twice

### ISSUE THREAD

**Issue by jcinis** [charmbracelet/glow#165]
![2020-10-10-08:58:01](https://user-images.githubusercontent.com/61810/95658368-161a4980-0ad7-11eb-9262-0bf03a9c090d.png)

Using glow version 1.0.1 on archlinux installed using the aur/glow 1.0.1-1 package.

**Comment by muesli** [comment]
Thank you! This has already been fixed in #163 and will be released as `v1.0.2` soon!
