### ISSUE TITLE
Href Link issue

### ISSUE THREAD

**Issue by rogeralsing** [charmbracelet/glow#169]
Not sure if this is Glow or Hyper term misbehaving.

Highlighting and styling works correctly. 

The dot is included in the link when clicking it. making the URL incorrect.

<img width="621" alt="Skärmavbild 2020-10-16 kl  13 37 28" src="https://user-images.githubusercontent.com/647031/96253951-c47d2d80-0fb4-11eb-9856-9f5cd682223c.png">

as you can see, the link is correctly highlighted, the dot there is white and not part of the highlighted section.
but the actual link content incorrectly includes the dot

making the URL incorrect when clicking it

**Comment by meowgorithm** [comment]
Hi! This appears to be an issue with Hyper; I'm not seeing the same behavior in other terminals.
