### ISSUE TITLE
Synchronize with Nextcloud Notes

### ISSUE THREAD

**Issue by stefan-niedermann** [charmbracelet/glow#170]
Would be awesome if the markdown notes could be synchronized with [Nextcloud Notes](https://apps.nextcloud.com/apps/notes) (see [API documentation](https://github.com/nextcloud/notes/blob/master/docs/api/v1.md)) 🙂

**Comment by caarlos0** [comment]
we actually removed networking functionalities from glow master, so I think this won't get in.

sorry for the delay!
