### ISSUE TITLE
go get fails with go1.15.3

### ISSUE THREAD

**Issue by voest** [charmbracelet/glow#171]
It seems like the Installation with `go get` fails at the moment on Arch Linux with `go version go1.15.3 linux/amd64`

```
go get github.com/charmbracelet/glow
# github.com/charmbracelet/glow/ui
go/src/github.com/charmbracelet/glow/ui/ui.go:57:23: too many arguments in call to tea.NewProgram
        have (func() (tea.Model, tea.Cmd), func(tea.Msg, tea.Model) (tea.Model, tea.Cmd), func(tea.Model) string)
        want (tea.Model)
go/src/github.com/charmbracelet/glow/ui/ui.go:211:3: cannot use m (type model) as type tea.Model in return argument:
        model does not implement tea.Model (missing Init method)
go/src/github.com/charmbracelet/glow/ui/ui.go:218:14: impossible type assertion:
        model does not implement tea.Model (missing Init method)
go/src/github.com/charmbracelet/glow/ui/ui.go:220:15: cannot use model literal (type model) as type tea.Model in return argument:
        model does not implement tea.Model (missing Init method)
go/src/github.com/charmbracelet/glow/ui/ui.go:414:14: impossible type assertion:
        model does not implement tea.Model (missing Init method)
```

**Comment by muesli** [comment]
Please enforce enabling Go modules:

`GO111MODULE=on go get github.com/charmbracelet/glow`

**Comment by voest** [comment]
Great, thank you. Would that hint be a good addition for the README?

**Comment by muesli** [comment]
Yeah you're right, I should probably update the README in that regard, even though Go 1.16 will also fix this situation.

**Comment by voest** [comment]
I think that could help people to start using `glow`. Especially on distribution where Go < 1.16 will be around for a while.

BTW: I really like `glow`. I've been looking around quite a while for a tool like this :slightly_smiling_face:

**Comment by muesli** [comment]
Again, you're absolutely right and I just fixed this now! Thanks for the kind words :heart:
