### ISSUE TITLE
un-known connection to id.charm.sh every time open a local markdown

### ISSUE THREAD

**Issue by vinbrule** [charmbracelet/glow#172]
Hi, when I run glow to view a local markdown file. It connects to id.charm.sh. Why is it? and how to disable this behavior?

Bests,

**Comment by muesli** [comment]
Thanks for bringing this to our attention, that shouldn't happen. Are you calling glow directly with a markdown file as an argument? (e.g. `glow foobar.md`)

**Comment by vinbrule** [comment]
thanks for quick response, i use glow without argument

**Comment by muesli** [comment]
If you start glow without any arguments it will open the TUI which will indeed check if you have any markdown stashes stored online. We're adding a flag that lets you disable any network activity.

**Comment by muesli** [comment]
We've added a `-l / --local` flag and a config file setting that makes glow work local-only.
