### ISSUE TITLE
markdown dialect?

### ISSUE THREAD

**Issue by Square252** [charmbracelet/glow#175]
Hi there,

Awesome project so far, but I can only use it in prod if it supports commonmark.
I can't find anything about the supported markdown specs. Does it also support commonmark?

**Comment by muesli** [comment]
Glow/Glamour support CommonMark 0.29 with some of the more popular extension (e.g. tables).

**Comment by Square252** [comment]
Awesome, thank you :+1: 
Love it already :smiling_face_with_three_hearts:
