### ISSUE TITLE
Headers 2 - 6 not rendered correctly, just raw text

### ISSUE THREAD

**Issue by trankchung** [charmbracelet/glow#178]
Glow is only renders header 1, for example `# Header1`, correctly. The rest of headers 2 through 6 render as raw text.

README.md example
```
# Heading 1
This is text below heading 1

## Heading 2
This is text below heading 2

### Heading 3
This is text below heading 3

#### Heading 4
This is text below heading 4

##### Heading 5
This is text below heading 5

###### Heading 6
This is text below heading 6
```

Output
![image](https://user-images.githubusercontent.com/573808/96374741-8dd51d80-1142-11eb-812f-553754814073.png)

**Comment by muesli** [comment]
There actually is a styling applied: the colors. If you prefer a different styling, it's really easy to adjust it yourself!

Just download `dark.json` from https://github.com/charmbracelet/glamour/tree/master/styles and edit it to your liking. You can pass your style file to glow with the `-s` flag or the `GLAMOUR_STYLE` environment variable.

If you come up with your own cool style, feel free to send a PR to the `glamour` repository. We'll soon add a gallery of user-contributed styles :heart:

**Comment by seanvaleo** [comment]
It would be nice if the default style did not show the `#`. As far as I can tell, in the glamour repository, there is also no example config for this behavior.

**Comment by stucash** [comment]
> It would be nice if the default style did not show the `#`. As far as I can tell, in the glamour repository, there is also no example config for this behavior.

It is now probably a good default given the colour rendering issue we are experiencing in xfce4 terminal: there's simply no colour no matter what theme you feed to glow. Does heading differ in size in terminal (my terminal simply displays the same size)? if not then colour is the only way to go to differ different headings. 

And colour fails right now. So it's compounded.
