### ISSUE TITLE
wacatac trojan in glow

### ISSUE THREAD

**Issue by AdityaG09** [charmbracelet/glow#192]
I recently git cloned and built glow using go. After a few minutes of using glow, I got a warning from Windows Security that the trojan was detected in the glow folder. Look into this. I freaked out and immediately deleted the folder, so I could not attach any screenshots.

**Comment by muesli** [comment]
If you built the binary yourself, and this is not a false positive, it would suggest you already had the malware on your machine.

Alternatively you can download our binaries from the release page which were built on a Linux machine, which I assume is fairly safe from Windows trojans.

**Comment by AdityaG09** [comment]
Possible too. Alright then. Thank you.
