### ISSUE TITLE
Package for Solus OS

### ISSUE THREAD

**Issue by Siilwyn** [charmbracelet/glow#203]
Would you consider packaging for [Solus](https://getsol.us/home/)?

There is a [Solus Packaging](https://getsol.us/articles/packaging/) page with instructions but I found it pretty daunting...

**Comment by muesli** [comment]
The more the merrier! However be aware that unless we can automate the builds with GoReleaser, we only point people to packages picked up and maintained by "official" sources. That means we would have to try and convince the Solus maintainers to adopt glow as a package.

Ideally we will have reproducible builds in the future, which will make it a lot easier to verify third-party packages.

**Comment by Siilwyn** [comment]
Cool! I did not see anything about eopkgs in the GoReleaser docs, but for posterity I have opened a package request issue: https://dev.getsol.us/T9415

**Comment by muesli** [comment]
@Siilwyn Thank you! Sounds like they've generally accepted the request but are now looking for a package maintainer. That's great news!
