### ISSUE TITLE
Not smoothly while scrolling with Magic Trackpad on MBP

### ISSUE THREAD

**Issue by vt128** [charmbracelet/glow#206]
Comparing with `less` 😢

**Comment by meowgorithm** [comment]
Hi! We added experimental mouse wheel support in `master`. You turn it on by running `glow -m`, `glow --mouse`, or by setting `mouse: true` in the config file. We'll close this issue once this setting is in the official release.

Note that this is experimental functionality, so we may change or remove the setting in the future. Also keep in mind that, at the moment, mouse support may disable text selection, which is why support is still experimental.

What terminal are you using, by the way? Some terminals (like [Kitty](https://sw.kovidgoyal.net/kitty/)) send up/down arrow keys when mouse mode is disabled, which is why the scrolling wasn't smooth.

**Comment by vt128** [comment]
I used iTerm2 Build 3.4.1, and found it's not smooth.

I used built-in Terminal app of macOS 10.15.7 (19H2), the scrolling is totally not functional.

**Comment by muesli** [comment]
@vt128 Did you try this with latest master and the `-m` option?

**Comment by vt128** [comment]
I attempted to, but seems the latest version hasn't been released yet?

```bash
❯ glow -m
Error: unknown shorthand flag: 'm' in -m
Usage:
  glow SOURCE [flags]
  glow [command]

Available Commands:
  config      Edit the glow config file
  help        Help about any command
  stash       Stash a markdown

Flags:
  -a, --all             show system files and directories (TUI-mode only)
      --config string   config file (default /Users/vej/Library/Preferences/glow/glow.yml)
  -h, --help            help for glow
  -l, --local           show local files only; no network (TUI-mode only)
  -p, --pager           display with pager
  -s, --style string    style name or JSON path (default "auto")
  -v, --version         version for glow
  -w, --width uint      word-wrap at width

Use "glow [command] --help" for more information about a command.

❯ brew upgrade glow
Updating Homebrew...
Warning: glow 1.1.0 already installed
```

**Comment by muesli** [comment]
No, you'd have to build master yourself or wait for the next release.

**Comment by meowgorithm** [comment]
This is bow available in the latest release.

**Comment by vt128** [comment]
@meowgorithm got the latest from homebrew, and `-m` works now. but ... it seems that the version number is broken? and `-m` is not found in help doc:

```bash
❯ brew upgrade glow
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

Warning: glow 1.2.0 already installed
❯ which glow
/usr/local/bin/glow
❯ glow -v
glow version unknown (built from source)
❯ glow -h

  Render markdown on the CLI, with pizzazz!

Usage:
  glow SOURCE [flags]
  glow [command]

Available Commands:
  config      Edit the glow config file
  help        Help about any command
  stash       Stash a markdown

Flags:
  -a, --all             show system files and directories (TUI-mode only)
      --config string   config file (default /Users/vej/Library/Preferences/glow/glow.yml)
  -h, --help            help for glow
  -l, --local           show local files only; no network (TUI-mode only)
  -p, --pager           display with pager
  -s, --style string    style name or JSON path (default "auto")
  -v, --version         version for glow
  -w, --width uint      word-wrap at width

Use "glow [command] --help" for more information about a command.
```

**Comment by meowgorithm** [comment]
Mouse functionality is "hidden" at the moment as it's experimental, which is why it's not in the help. See details in the [previous comment](https://github.com/charmbracelet/glow/issues/206#issuecomment-731393592).

As for the version number, did you build from source or install a binary?

**Comment by vt128** [comment]
@meowgorithm Cool, I ignored that. The **disabled text selection** is a problem --- I can't scroll and select at the same, like `less`.

**Comment by meowgorithm** [comment]
Right, that as also was noted in the previous comment, and that's why mouse support is currently considered experimental.

**Comment by vt128** [comment]
Looking forward to the production version of this feature 👨🏻‍💻
