### ISSUE TITLE
Where glow stores stashed notes?

### ISSUE THREAD

**Issue by asakura42** [charmbracelet/glow#209]

**Comment by toby** [comment]
Hi, good question! Stashed markdown is encrypted on your machine then stored in the Charm Cloud. The first time you `glow stash` on a machine, we'll generate SSH keys and use them to create an account (or link to an existing account) as well as for encryption key management.

You an find out more at the `charm` project (which `glow` uses as a library): https://github.com/charmbracelet/charm

Also happy to answer any question in Slack, email vt100@charm.sh for an invite.
