### ISSUE TITLE
Did anyone notice that the Official Github CLI uses Glow?

### ISSUE THREAD

**Issue by wantyapps** [charmbracelet/glow#210]
When you type `gh repo view` in the terminal, the Github CLI will show you a preview of the README.md file inside a Github repository. But, when you look at the preview and compare it to the Glow preview there is a 100% match.

**Comment by wantyapps** [comment]
BTW: Sorry for the Non-Issue question, but this really triggered me.

**Comment by muesli** [comment]
Correct, the GitHub CLI uses `glow`'s rendering engine, `glamour`: https://github.com/charmbracelet/glamour/

**Comment by wantyapps** [comment]
Wow! Thanks a lot for the information. Another question before I leave from this PR: Can I use Glow's binary in my own repository? https://github.com/wantyapps/wantyappsOS.git

**Comment by muesli** [comment]
I wouldn't recommend to copy a binary to a git repository, but technically speaking there's nothing stopping you.
