### ISSUE TITLE
Option to create new stashed file

### ISSUE THREAD

**Issue by shitchell** [charmbracelet/glow#215]
After charmbracelet/glow#182 is implemented, it would be nice to have the option to create a new file from within glow. On the main page, when viewing stashed files, type 'n' to create and begin editing a new file that will be added to the user's stash.

**Proposed flow**

1. At the main page, user types 'n'
2. The cursor is moved to the top of the page
3. A new entry is added to the list of stashed files
4. The user is prompted to enter a memo for the new entry (just like editing the memo for a normal file)
> **Memo:** New File
> **Just now**
5. After the user hits enter, a temporary file is created locally and opened with the editor
6. Once the editor exits, the temporary file is stashed with the given memo and deleted locally

At present, I have to create a new file, edit it, stash it, and then delete it. This enhancement would make glow pretty much a standalone (ignoring the fact that you need an external editor) tool to access, edit, and create files across devices.

**Comment by kjhughes097** [comment]
+1 for adding `n` to create a new file

**Comment by caarlos0** [comment]
stashing was removed from master.
