### ISSUE TITLE
Option to export/save stashed document

### ISSUE THREAD

**Issue by shitchell** [charmbracelet/glow#226]
It would be nice to be able to save/export stashed documents to a local file. At present, if you delete the local copy of a stashed file or switch machines, you simply can't get the original document back.

Proposed flow:

* Type keyboard shortcut *[1]* to trigger exporting file
* A prompt *[2]* will appear like the one used to set the memo for a document (but with the title "Choose Filename")
* The prompt is pre-populated with the current note / filename
* If the user types `esc`
  * Cancel and return to normal pager view
* If the user types `enter`
  * If a file with that name exists, ask the user if they want to overwrite the file
    * If the user types `y`
      * Save the file and return to normal pager view
    * If the user types `n` (or anything other than `y`)
      * Return to the "Choose Filename" prompt
  * If a file with that name doesn't exist
    * Save the file and return to normal pager view
* A status message is displayed with a success/error/cancel message

*[1] The exact key used isn't terribly important, but I propose `s` for save. It's used to stash a local file, so it seems fitting that its behavior would reverse for stashed files to save them locally. `e` for export is taken by the pending editor feature (charmbracelet/glow#225), and no other keybinding makes nearly as much sense.*
*[2] Use this prompt for the filename, with "Set Memo" replaced by "Choose Filename"*
![set-memo](https://user-images.githubusercontent.com/621412/102476081-ae2d3580-4028-11eb-929f-6cf3155356bb.png)

**Comment by caarlos0** [comment]
stashes were removed from master.
