### ISSUE TITLE
Set pager option from within glow.yml

### ISSUE THREAD

**Issue by tricarte** [charmbracelet/glow#231]
It seems we don't have an option to enable pager support inside glow.yml config file.
These are what I've tried:
* pager: true
* pager: ${PAGER}
* pager: "/usr/bin/less"
* pager: "less"

But none of them worked.

**Comment by muesli** [comment]
Correct, it currently only parses the `$PAGER` env-var.

**Comment by lestrrat** [comment]
@muesli Hi, I took the liberty of making a PR to fix this issue. Please review, and let me know! :)

Thanks for the awesome tool!
