### ISSUE TITLE
REQUEST: support for arm64 architecture 

### ISSUE THREAD

**Issue by samuelgoestomars2607** [charmbracelet/glow#232]
It would be nice to have a stable version that runs on arm64. Now more than ever, because arm is getting more popular over time.

**Comment by muesli** [comment]
There are arm64 releases for various platforms. I assume you mean support for the new Apple M1 chips? We'll support them as soon as Go 1.16 is out.

**Comment by samuelgoestomars2607** [comment]
support for M1 is fine, but my problem is that I am working on a raspberry-pi and tried to install the snap but I got the error that there is no stable version of glow for arm64.

**Comment by meowgorithm** [comment]
That sounds like an issue with the snap. We don't actually provide a snap release, so it sounds like whoever published it didn't include ARM support.

That said, you can download a ARM build for the Raspberry Pi on the [releases page](https://github.com/charmbracelet/glow/releases). You most likely need the ARM7 version.

**Comment by damarshall** [comment]
install the arm64.deb on a Raspberry Pi4. It works fine, use it on several of them.

**Comment by samuelgoestomars2607** [comment]
Thank you! this worked perfectly!
