### ISSUE TITLE
List files with .mkd extension in TUI

### ISSUE THREAD

**Issue by maxigaz** [charmbracelet/glow#233]
Some developers use the extension `.mkd` instead of `.md` for their documentation. When I run glow v1.3.0 without any arguments for browsing these files, they don’t show up in the TUI.

(Opening them directly with `glow readme.mkd` works, though.)

**Comment by muesli** [comment]
Thank you! I've added a variety of supported file extensions now in git master. This will be supported in the next release.

**Comment by prosoitos** [comment]
Would you mind adding `.qmd` to the list?

Those are [Quarto](https://quarto.org/) files—Markdown with code blocks. Quarto is becoming quite a popular tool.

`glow` renders them too when they are called as arguments, but they don't show in the TUI.

Thanks!
