### ISSUE TITLE
Passing a folder or directory should open the textual user interface

### ISSUE THREAD

**Issue by j-james** [charmbracelet/glow#234]
The current behavior of `glow <directory-name>` opens a README file within the directory if it exists. 

It'd be much more useful if `glow <directory-name>` opened the textual user interface within that directory context instead - like `cd <directory-name>; glow; cd ..`

**Comment by meowgorithm** [comment]
Good call, Glow should totally behave this way.

**Comment by meowgorithm** [comment]
Alright, this is now in `master`. We'll close this issue when the feature lands in the next release.

**Comment by muesli** [comment]
Part of v1.4.0.
