### ISSUE TITLE
Support AsciiDoc?

### ISSUE THREAD

**Issue by tadayosi** [charmbracelet/glow#243]
This is a great tool and it would be even better if it could read [AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/) files as well. Thanks!

**Comment by keblek** [comment]
one work around for this is to use pandoc to convert to md

**Comment by boydkelly** [comment]
The workaround is awkward.  Not advantageous to keep multiple versions of documents that can change at any point.   And since Asciidoc is becoming a standard....  https://asciidoc-wg.eclipse.org/  It should be even more interesting to support, as opposed to all the html and other stuff added to markdown in its multiple flavours.

**Comment by ubiquitousthey** [comment]
I will second the request to support asciidoc.  It is so much more powerful and standardized than MD.  While this might mean it would be more difficult, I think it might mean a better experience.  There are Ruby, Javascript, and Java implementations.  I wouldn't be surprised to see a Go implementation being worked on somewhere.

**Comment by dhutty-numo** [comment]
Yes, there is a golang lib for asciidoc->html: https://github.com/bytesparadise/libasciidoc
I would love to see support added to glow.

**Comment by skatkov** [comment]
Another request to support AsciiDoc. :)

**Comment by dezren39** [comment]
it would be really great if asciidoc was supported, i could even see use in glow being able to quickly convert output between markdown, asciidoc, and html. Is glow built in a way such that different formats can be added matching a specific interface? I'm guessing would this require bigger changes in the structure of the project?

**Comment by randybb** [comment]
Native support for AsciiDoc would be great. I have been using ascidoc since 2009 for all my work related notes.

**Comment by caarlos0** [comment]
I think we're gonna focus on markdown for now.

thanks for the issue, sorry for the delay
