### ISSUE TITLE
Make the stash feature pluggable

### ISSUE THREAD

**Issue by marcosnils** [charmbracelet/glow#245]
Hi there, big fan of glow and all things Charmbracelet. 

I'd love to stash my notes somewhere else besides charm cloud. Reason for this is that for some of them I don't really need encryption and I'd like to browse them in my cell phone using evernote, google tasks or any other note taking app. 

The way this could be achieved is by making the stash feature pluggable. One approach would be using something like https://github.com/hashicorp/go-plugin which is the same architecture a lot of HashiCorp tools use. I'm happy to work on a PR is this could be useful to someone else.

**Comment by muesli** [comment]
While not really "pluggable", you can disable all network features in glow's config. We're thinking about making `glow` a bit more modular and customizable however.

**Comment by belibug** [comment]
`glow stash somefile.md` still works after disabling network feature in config. It does remove network features in some places but not all. How do I completely opt out.

**Comment by caarlos0** [comment]
stash was removed from master.
