### ISSUE TITLE
Request: Configuration or setting to disable stash

### ISSUE THREAD

**Issue by James-Firth** [charmbracelet/glow#249]
For those that just want an _awesome_ markdown viewer, it would be nice to be able to disable the stash feature, especially on a work machine.

**Comment by meowgorithm** [comment]
Nice to hear you think Glow is awesome! To disable the stash you can set `local` to `true` in the config. To edit the config just run`glow config`.

https://github.com/charmbracelet/glow#the-config-file

**Comment by James-Firth** [comment]
@meowgorithm Oh awesome! My bad for not digging into the docs enough. Thanks for the quick reply!
