### ISSUE TITLE
Version parameter adds output string "29;1R"

### ISSUE THREAD

**Issue by Spreadcat** [charmbracelet/glow#265]
When running the version parameter, additional output is created:

```bash
$ glow --version
glow version 1.4.0 (4f9ad67)
$ 29;1R
```

- `TERM` contains `rxvt`
- This happens with `--version` and `-v` equally.

**Comment by meowgorithm** [comment]
Which OS, terminal emulator and shell are you using?

**Comment by Spreadcat** [comment]
- OS: Fedora 33
- Emulator: urxvt
- Shell: bash, 5.0.17

I cannot reproduce the issue with _terminator_ or _alacritty_

**Comment by meowgorithm** [comment]
Thanks for that. I can also reproduce this in urxvt.

Some notes with regard to this bug:
* This is probably related to recent [Termenv](https://github.com/charmbracelet/termenv) updates (as noted per @muesli)
* I've noticed when building [Bubble Tea](https://github.com/charmbracelet/bubbletea) that urxvt has certain idiosyncrasies compared to other terminal emulators

**Comment by muesli** [comment]
This has been fixed in Termenv v0.8.2, and glow's dependency on it has been bumped. This will be released as v1.4.1 tomorrow.

**Comment by Spreadcat** [comment]
> This will be released as v1.4.1 tomorrow.

tomorrow? ;)

**Comment by muesli** [comment]
@Spreadcat Sorry for the delay, we have pushed out a bunch of releases this week and needed to get the order right, as `glow` depends on our other libraries, like `bubbletea`. 1.4.1 is out!
