### ISSUE TITLE
glow | more

### ISSUE THREAD

**Issue by UltiRequiem** [charmbracelet/glow#266]
https://user-images.githubusercontent.com/71897736/115608183-8d613f00-a2ab-11eb-8cf6-b500d0b1f36e.mp4

Expected behavior: Colors are maintained

It also happens inside vim

https://user-images.githubusercontent.com/71897736/115608748-4c1d5f00-a2ac-11eb-812d-ee522f5bdcd7.mp4

**Comment by maxigaz** [comment]
I don’t use `more`, but I’ve just managed to make it work with `less`. Here’s what I did.

First, run `glow config` and add the following:

```
pager: less
```

Then, use `less`’s option `-R` (you may want to add it to your .bashrc or .zshrc):

```
export LESS=' -R '
```

Finally, tell glow to use the specified pager:

```
glow -p README.md
```

It not only preserves colours for me, but tables are shown correctly as well.

**Comment by UltiRequiem** [comment]
Thanks!

**Comment by gongyibei** [comment]
`unbuffer glow README.md | less`
