### ISSUE TITLE
No installation for rpm distros

### ISSUE THREAD

**Issue by boydkelly** [charmbracelet/glow#267]
Hey you guys,

It is a big disadvantage for you not to produce rpms for SUSE (Europe), Red Hat, Fedora, and derivatives.   Yes we can install directly via go.   The only issue is for you not me.  Your adoption will be slower.

**Comment by muesli** [comment]
You can find various RPMs here: https://github.com/charmbracelet/glow/releases

**Comment by boydkelly** [comment]
Uh...  Maybe put that in your README!  https://github.com/charmbracelet/glow/blob/master/README.md

**Comment by muesli** [comment]
The README:

"Or download a binary from the releases page. MacOS, Linux, Windows, FreeBSD, and OpenBSD binaries are available, as well as Debian, RPM, and Alpine packages."
