### ISSUE TITLE
Feature: Add man page

### ISSUE THREAD

**Issue by ifrendas** [charmbracelet/glow#269]
Could a man page be added?

**Comment by muesli** [comment]
Of course! Do you want to write one?

**Comment by ifrendas** [comment]
I'd be open to doing that. Where would you like me to put it in the repository when I am done?

**Comment by muesli** [comment]
I would simply put it in the main directory, alongside the `main.go`.

**Comment by FilBot3** [comment]
Here is a link to generate the reference.

* PR: https://github.com/charmbracelet/glow/pull/271
