### ISSUE TITLE
Force color (from fzf --preview)

### ISSUE THREAD

**Issue by mrzv** [charmbracelet/glow#280]
I'd like to use glow with `fzf`, when I run `fzf --preview "glow {1}"`, it works, but I don't get the colors. I'm guessing there is a problem with the detection of terminal capabilities, or something like that. The same problem happens with `fzf --preview "bat {1}"`, but it can be overcome with `... "bat --color always {1}"`. Is there a way to get the same behavior with glow? I.e., to force it to emit the color codes?

**Comment by muesli** [comment]
@mrzv glow probably detects stdout to be rewritten and it not directly printing to a terminal. You can still enforce a style by running glow with `--style dark` (for example).

**Comment by meowgorithm** [comment]
So to answer your question directly, `fzf --preview "glow --style dark {1}` will do exactly what you need.

**Comment by mrzv** [comment]
Perfect. That works. Thank you.
