### ISSUE TITLE
glow doesnt show files that are gitignored at a specific folder

### ISSUE THREAD

**Issue by alexzanderr** [charmbracelet/glow#283]

**Comment by muesli** [comment]
That's correct and intentional.

**Comment by meowgorithm** [comment]
That said, you can override the behavior with `glow -a` / `glow --all`.

**Comment by alexzanderr** [comment]
i just tried. it doesnt work.

maybe because in gitignore i have the entire folder (the file i want is here) ignored?

**Comment by muesli** [comment]
Closing in favor of #285.
