### ISSUE TITLE
[question] is there a live update function?

### ISSUE THREAD

**Issue by alexzanderr** [charmbracelet/glow#284]
while im editing a markdown and i have opened with glow that file, does glow have live update while im writing to the markdown file?

**Comment by muesli** [comment]
Not yet, but it's certainly high up on our personal wish list as well. It's a non-trivial issue, but we'll eventually get to it. Stay tuned for this!

**Comment by alexzanderr** [comment]
nice.

**Comment by muesli** [comment]
Closing a few tickets describing the same feature. Let's track this in #135, which was the first ticket suggesting it.
