### ISSUE TITLE
Rendering colors are cool, but make font size and properties like github

### ISSUE THREAD

**Issue by mohamadali-halwani** [charmbracelet/glow#291]
I think it's better if an h2 text was displayed in a bigger font than just leaving the ## there while changing the color

Writing an h2 text renders to this:
```## this is an h2 line of text```
instead of a bigger font
I think it's better to make a rendering style just like the one in github, or please guide me to the files I need to change in order to get this effect.
Thanks

**Comment by marcelarie** [comment]
Using special characters could be fun 😄 

	██      ██ ██   ██ ███████     ████████ ██   ██ ██ ███████ 
	██      ██ ██  ██  ██             ██    ██   ██ ██ ██      
	██      ██ █████   █████          ██    ███████ ██ ███████ 
	██      ██ ██  ██  ██             ██    ██   ██ ██      ██ 
	███████ ██ ██   ██ ███████        ██    ██   ██ ██ ███████ 

	░█─── ▀█▀ ░█─▄▀ ░█▀▀▀ 　 ▀▀█▀▀ ░█─░█ ▀█▀ ░█▀▀▀█ 
	░█─── ░█─ ░█▀▄─ ░█▀▀▀ 　 ─░█── ░█▀▀█ ░█─ ─▀▀▀▄▄ 
	░█▄▄█ ▄█▄ ░█─░█ ░█▄▄▄ 　 ─░█── ░█─░█ ▄█▄ ░█▄▄▄█

	█░░ █ █▄▀ █▀▀   ▀█▀ █░█ █ █▀
	█▄▄ █ █░█ ██▄   ░█░ █▀█ █ ▄█

	🇱​​​​​🇮​​​​​🇰​​​​​🇪​​​​​ 🇹​​​​​🇭​​​​​🇮​​​​​🇸

	𝕃𝕀𝕂𝔼 𝕋ℍ𝕀𝕊
	𝙇𝙄𝙆𝙀 𝙏𝙃𝙄𝙎
	𝐋𝐈𝐊𝐄 𝐓𝐇𝐈𝐒
	ＬＩＫＥ ＴＨＩＳ
	ₗᵢₖₑ ₜₕᵢₛ

**Comment by dsldata** [comment]
Thanks!
