### ISSUE TITLE
Bullet Points aren't rendering properly when used with a pager on Windows

### ISSUE THREAD

**Issue by Jarmos-san** [charmbracelet/glow#296]
Glow works wonderful on Windows, the bullet points are rendered nicely when not used with the `-p` flag. Screenshot attached for reference:

**Glow's output w/o the `-p` flag**:

![image](https://user-images.githubusercontent.com/31373860/134537768-7dec3bc5-c8d7-4f85-a3e7-f2481cb3f31d.png)

But the output breaks when used with a pager, screenshot below for reference.

**Glow's output with the `-p` flag**:

![image](https://user-images.githubusercontent.com/31373860/134538297-88c3a341-3a82-469f-bd0f-7d75c88b90b6.png)

For further information, I'm using [less-Windows](https://github.com/jftuga/less-Windows) on a Windows 10 machine for all my paging requirements. So, other CLI tools work perfectly fine w/o any issues.

Let me know if I need to provide any more information for further debugging.

**Comment by meowgorithm** [comment]
Hi! I believe this has to do with `less.exe` (and Windows to some degree) not interpreting input as `UTF-8`. If you open the markdown file with less-windows directly (i.e. `less.exe README.md`) you'll likely also see bullets rendering improperly. Printing the file to the terminal (i.e. `cat README.md`) should mis-render the bullets as well.

The only solution I know of is to set your system locale to UTF-8. In the control panel:

* Go to **Language Settings**
* Click **Administrative language settings**
* Click **Change system locale**
* Tick **Beta: Use Unicode UTF-8 for worldwide language support**
* Reboot

After that, both `less.exe` and `cat`ing out the file will produce proper bullet characters. Of course, the feature is marked beta, so _caveat emptor_, as they say. I, unfortunately, don't use Windows heavily enough to know if there are any risks involved.

**Comment by Jarmos-san** [comment]
Wonderful! The solution shared above did fix the issue.

_Windows 10_ being _Windows_, has made looking out for this settings option slightly hidden away. So, here's a screen cap of how I enabled the settings below.

![6GQN2BUsLz](https://user-images.githubusercontent.com/31373860/134606619-b02490a0-dbc3-45ac-9e95-15cc567d78b4.gif)

Closing thread as it's fixed.
