### ISSUE TITLE
FEATURE REQUEST: Slide Show Presentation Mode

### ISSUE THREAD

**Issue by FilBot3** [charmbracelet/glow#297]
# Feature Request

I would like to request that the feature of being able to launch a Markdown document into slides delineated by header be added. I have no idea how to code this up myself. I can learn it, but it will take time.

**Comment by meowgorithm** [comment]
Check out [Slides](https://github.com/maaslalani/slides) by @maaslalani! It does exactly what you're asking for.

It was built with [Bubble Tea](https://github.com/charmbracelet/bubbletea), the same TUI framework powering Glow.

**Comment by FilBot3** [comment]
Well, hot dog. That's spiffy! Thank you!
