### ISSUE TITLE
Pipe escape codes on Windows

### ISSUE THREAD

**Issue by nzbart** [charmbracelet/glow#299]
I'd like to be able to run `glow` against a markdown file and redirect the output, including terminal escape codes, to a file. Right now, if I run the following, only plain text is written to `file.txt`:

```powershell
glow readme.markdown > file.txt
```

I can work around this limitation by running the following commands, but it isn't an overly clean approach, and also outputs to standard output:

```powershell
$env:PAGER='tee file.txt'
glow readme.markdown -p
```

It would be great to have the ability to override the default behaviour and allow redirecting of the escape codes.

For reference, an example of another application that allows this is ripgrep:
```
 --color <WHEN>
    This flag controls when to use colors. The default setting is 'auto', which
    means ripgrep will try to guess when to use colors. For example, if ripgrep is
    printing to a terminal, then it will use colors, but if it is redirected to a
    file or a pipe, then it will suppress color output. ripgrep will suppress color
    output in some other circumstances as well. For example, if the TERM
    environment variable is not set or set to 'dumb', then ripgrep will not use
    colors.

    The possible values for this flag are:

        never    Colors will never be used.
        auto     The default. ripgrep tries to be smart.
        always   Colors will always be used regardless of where output is sent.
        ansi     Like 'always', but emits ANSI escapes (even in a Windows console).
```

**Comment by muesli** [comment]
You can enforce a particular style with `-s`, e.g.:

```bash
glow -s dark README.md > file.txt
```

**Comment by nzbart** [comment]
@muesli fantastic! As simple as that! 

Thanks for responding so quickly.
