### ISSUE TITLE
node dist (thanks to webassembly)

### ISSUE THREAD

**Issue by abernier** [charmbracelet/glow#303]
Node.js is supporting webassembly: https://nodejs.dev/learn/nodejs-with-webassembly

What about compiling a `.wasm` build in order to execute it from Node.js? What about:

```sh
$ npm i glow
```

I have currently no experience with go, but could help about Node/npm.

Found that quick tutorial https://egghead.io/lessons/go-compile-and-execute-a-go-webassembly-program-with-node for now

**Comment by wperron** [comment]
Hey 👋  not a maintainer or even a contributor, but what would be the use case for this?

**Comment by muesli** [comment]
In all theory this is possible with `GOOS=js GOARCH=wasm go build`. In reality however, there are still a few dependencies that aren't prepared for wasm builds, `termenv`, `viper`, `console`, and `clipboard` among them.

**Comment by caarlos0** [comment]
not in the scope of the project for now.
sorry for the delay, closing!

**Comment by meowgorithm** [comment]
Side note that if we ever do move forward with this, the place to watch would be [Bubble Tea](https://github.com/charmbracelet/bubbletea):

https://github.com/charmbracelet/bubbletea/pull/887
https://github.com/charmbracelet/bubbletea/pull/748
