### ISSUE TITLE
Option to quickly open file in $EDITOR

### ISSUE THREAD

**Issue by Yush08** [charmbracelet/glow#309]
I wanted to edit the files as I go read them in glow, anyway I can quickly switch to and from my editor?

**Comment by vielmetti** [comment]
Same experience here - I expected an "e" command to be "edit".

**Comment by Yush08** [comment]
Any update on this?

**Comment by BaldFabi** [comment]
This issue is actually a dup of #182 I think

**Comment by muesli** [comment]
@BaldFabi Thanks, you're absolutely right. Closing this issue.
