### ISSUE TITLE
Feature Request: LaTeX preview

### ISSUE THREAD

**Issue by axieax** [charmbracelet/glow#312]
Hi,
Love using glow so far. It would be amazing if glow can show LaTex or TeX previews as well. Is this a possible feature?
Thanks!

**Comment by muesli** [comment]
Thank you, great to hear you love glow! I can understand the desire for LaTeX support, but I'll be honest: this is probably out of scope for glow :smiley:

**Comment by caarlos0** [comment]
closing as out of scope.
