### ISSUE TITLE
How to choose syntax color theme

### ISSUE THREAD

**Issue by anishmittal2020** [charmbracelet/glow#317]
As this was merged, [Let user pick a syntax color theme in Gold's style config by muesli · Pull Request #30 · charmbracelet/glow](https://github.com/charmbracelet/glow/pull/30), could you please say how to use this?

**Comment by muesli** [comment]
This can be configured as part of a glamour style: https://github.com/charmbracelet/glamour/tree/master/styles

You can create your own style.json and launch glow with it: `glow -s style.json`.
