### ISSUE TITLE
Arch Linux packages are not available

### ISSUE THREAD

**Issue by onnyyonn** [charmbracelet/glow#322]
The README mentions that the package can be installed in Arch Linux with `pacman -S glow`. But it throws error `target not found: glow`. On the other hand, it seems that the packages `glow` and `glow-bin` were available at AUR at some point, but not anymore. Is the package still available in Arch repository or AUR?

**Comment by muesli** [comment]
It's certainly in the community repo:

https://archlinux.org/packages/community/x86_64/glow/

Make sure that's enabled and your package definitions are up-to-date: `pacman -Syu`

**Comment by Einenlum** [comment]
Coming from Manjaro, I can confirm the problem. It's weird. I have a lot of community packages installed.
Glow isn't there nor in Aur packages.

**Comment by muesli** [comment]
I guess Manjaro's community repo didn't pick it up yet. The AUR packages were deleted by Arch maintainers after `glow` got accepted into its own community repo, which makes this a bit awkward. I'd recommend to reach out to Manjaro maintainers and request the package.

In the meantime, here's the AUR PKGBUILD I've maintained myself before. Place it in an empty dir and run `makepkg` to create a glow package. You can then install it with `pacman -U glow-1.4.1-1-x86_64.pkg.tar.zst`.

```
pkgname=glow
pkgver=1.4.1
pkgrel=1
pkgdesc="Markdown renderer for the CLI"
arch=('x86_64' 'i686' 'armv6h' 'armv7h' 'aarch64')
url="https://github.com/charmbracelet/${pkgname}"
license=('MIT')
depends=('glibc')
makedepends=('git' 'go')
source=("${url}/archive/v${pkgver}/${pkgname}-${pkgver}.tar.gz")
sha256sums=('ff6dfd7568f0bac5144ffa3a429ed956dcbdb531487ef6e38ac61365322c9601')

build() {
    local commit
    local extraflags
    commit=$(zcat ${pkgname}-${pkgver}.tar.gz | git get-tar-commit-id)
    extraflags="-X main.Version=${pkgver} -X main.CommitSHA=${commit}"

    cd "$pkgname-$pkgver"

    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"

    go build \
        -trimpath \
        -buildmode=pie \
        -mod=readonly \
        -modcacherw \
        -ldflags "${extraflags} -linkmode external -extldflags \"${LDFLAGS}\"" \
        -o "$pkgname" .
}

package() {
    cd "$pkgname-$pkgver"

    install -Dm755 "$pkgname" "$pkgdir/usr/bin/$pkgname"
    install -Dm644 "LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

**Comment by Einenlum** [comment]
Awesome, thank you very much @muesli.

**Comment by onnyyonn** [comment]
Manjaro stable repo is generally 2-3 weeks behind Arch stable repo. So I am guessing it'll show up in due time.
