### ISSUE TITLE
Change Stash-server 

### ISSUE THREAD

**Issue by bauminao** [charmbracelet/glow#324]
I have a self-hosted sandbox.

Installed charm and read I can use ``` export CHARM_HOST=burrito.example.com ``` to point to the server [Docu-link](https://github.com/charmbracelet/charm#self-hosting)

But seems, glow is hard-coded to at least ``` id.charm.sh ``` 
At least I read this as error within glow. 

How can I change this?

**Comment by muesli** [comment]
We're working on this in the `beta` branch: https://github.com/charmbracelet/glow/tree/beta

**Comment by caarlos0** [comment]
stashes were removed from master.
