### ISSUE TITLE
Unstash files from stash

### ISSUE THREAD

**Issue by rkochar** [charmbracelet/glow#325]
I did not see instructions for unstashing a file on README.md, may I request you to add it? (also what are they?)

**Comment by toby** [comment]
Hi! If you press `x` on the stashed item, it will delete it from your stash. You can view all of the available commands in the lower part of the screen.

When an item is stashed, it's fully encrypted on your machine, then stored in the cloud. There's also a new beta version of `glow` that allows you to self-host the cloud if you'd rather. It's not released yet, but you can view it in this branch: https://github.com/charmbracelet/glow/tree/beta

**Comment by rkochar** [comment]
Thanks for the quick response. `x` does not work for me and I don't see the `x` option in the menu at the bottom either. I have Ubuntu 20.04.3 LTS and I downloaded `glow_1.4.1_linux_386.deb`. Maybe the option is added to newer versions?

**Comment by toby** [comment]
It should be there in 1.4.1. Does it look like this when you get into your stash?

![02-05-22-10-41-19](https://user-images.githubusercontent.com/83556/152650498-565be729-acf5-4db2-8633-7b32722c194e.png)

**Comment by rkochar** [comment]
Aha, indeed. I was searching in the first section. Would be great if you add this to README.
