### ISSUE TITLE
Support XDG paths on macOS

### ISSUE THREAD

**Issue by h0adp0re** [charmbracelet/glow#328]
It'd be great if glow would read its config from `XDG_CONFIG_HOME` instead of `~/Library/Preferences/glow/glow.yml` on macOS.

I frankly don't know anyone who uses `~/Library` for any kind of configuration for CLI tools.

**Comment by knpwrs** [comment]
I just ran into this today. I would love to put a glow config in my dotfiles repo but I would have to special case glow since everything else goes in `XDG_CONFIG_HOME`.
