### ISSUE TITLE
Optionally remove closing message

### ISSUE THREAD

**Issue by decentral1se** [charmbracelet/glow#329]
Lovely tool & sorry for the weird request but I wrap this tool in the CLI environment with another name that is not `glow`. So, when users close the tool, they see "Thanks for using Glow!" which is confusing. Would it be possible to turn this off? Thanks :pray:

**Comment by decentral1se** [comment]
In https://github.com/charmbracelet/glow#the-config-file this could be:

```yaml
goodbye: false
```

Can submit a PR if that seems OK?

**Comment by muesli** [comment]
I think we'll just remove the gimmicky message altogether, so we don't need to introduce a config option for this.

**Comment by decentral1se** [comment]
> I think we'll just remove the gimmicky message altogether, so we don't need to introduce a config option for this.

Cool! Removed in https://github.com/charmbracelet/glow/pull/331/commits/64651d6549fa510a95b1e81cd79b38ffac54a377 :+1:

**Comment by aral** [comment]
Looks like the PR was closed without getting merged. Would be nice to remove that message. In a Linux environment if a tool prints out a message after completion, I tend to think something went wrong. It’s quite jarring :)

**Comment by muesli** [comment]
@aral Yeah, I don't think we're opposed to that. It was a bit gimmicky (and we love gimmicky stuff), but we may remove it soon.

**Comment by maaslalani** [comment]
Fixed by https://github.com/charmbracelet/glow/pull/359
