### ISSUE TITLE
Garbled output with -p and most

### ISSUE THREAD

**Issue by reitzig** [charmbracelet/glow#332]
I want to read a markdown file pager-style, not by scrolling in the shell. So I use `-p`; `most` is my pager. Compare:

`glow -p README.md`:
![image](https://user-images.githubusercontent.com/4246780/159804742-7d5b6834-9e2b-4e1c-afed-e11e1e3a1ada.png)

`glow README.md`:
![image](https://user-images.githubusercontent.com/4246780/159804819-b84c5176-b5bc-48fb-a510-6adc0f86adb2.png)

`glow README.md | most`
![image](https://user-images.githubusercontent.com/4246780/159804908-858f90d2-a5ab-499a-9e6b-cbd67bd8d73f.png)

_Workaround:_ `glow .` or `glow --all` and select the file.

Not sure whether the problem is actually with glow, not most (most _does_ show colors in other cases, e.g. when showing man pages). So I guess I'll spin this as a feature request: please add an option (that I can make the default through the config file) that opens the given file in "pager mode" directly (without the external pager).

```
❯ glow --version
glow version 1.4.1 (4863f57)
❯ most --version
MOST version 5.0.0 (S-Lang version 2.3.2)
 *Note: This executable was compiled against S-Lang 2.3.1
```

**Comment by zach-is-my-name** [comment]
Pretty sure these are ansi codes that your pager is not configured to recognize.  Search the internet or the less docs for the less -r and see if there's an equivalent flag for most

**Comment by reitzig** [comment]
I was only looking for color; searching for "control characters", `-v` might help. But how do I test that? I don't see a way to pass pager flags t `glow`; it'd have to add the option automatically on `-p` the way it does for `less`, wouldn't it?

I'd still rather go to glow's "pager" directly, anyway, instead of printing to the shell. Should I open a separate ticket for that?

**Comment by zach-is-my-name** [comment]
You can set the flags in less in their env's or you can also pipe to glow with `glow -`

**Comment by gtsiam** [comment]
What I did: set `MANPAGER` to `most` (so now only man uses most) and `PAGER` to `less -r` (which apparently is the default used by glow if pager is unset. You could also unset `PAGER` to have the same effect).

Not really a solution, but it should get you up and running at least...

**Comment by muesli** [comment]
I think this may just be a `most` version that doesn't support RGB colors yet - the most recent releases do however.

As such, I can't reproduce this issue anymore, but here are a few tips:

- if you unset your `COLORTERM` environment variable to `yes` or `true`, glow should default to rendering ANSI256 colors, which your version of `most` should understand. In such cases setting the `PAGER` to `most` works fine.

- piping glow's output to other programs will disable styles and color rendering, as it detects not being connected to a terminal. You can override this by setting `CLICOLOR_FORCE` to `true`.
