### ISSUE TITLE
Support other Readme spellings if github repo url is providen 

### ISSUE THREAD

**Issue by xNaCly** [charmbracelet/glow#338]
# Description:
I would love for glow to support various spelling and extensions for Readmes, such as:
- no extension (c projects often use a simplified markdown syntax, but this could still be rendered)
- ignore case and just render `Readme` and `README`

I have tested glow with the following two repos, both readmes were not printed:
## First repo:
- https://github.com/xNaCly/netflix-rpc
```
$: glow github.com/xnacly/netflix-rpc
Error: can't find README in GitHub repository
```
Readme name: `Readme.md`

## Second repo:
- https://github.com/xNaCly/pgmE
```
$: glow github.com/xnacly/pgme
Error: cant't find README in GitHub repository
```
Readme name: `README`

**Comment by caarlos0** [comment]
this should be fixed on master
