### ISSUE TITLE
Adding `go install` to the installation instructions in README.md

### ISSUE THREAD

**Issue by krader1961** [charmbracelet/glow#360]
I was modifying the [Elvish shell](https://github.com/elves/elvish) to use `glow` to dynamically generate a Go source file that contains documentation for the shell's builtin functions and variables. I ultimately decided that the simplest, most future proof, mechanism (given the Elvish is also written in Go and hosted on Github) was to modify its CI workflow with these lines:

```
- name: Install glow to generate the documentation for the "help" command
   run: go install github.com/charmbracelet/glow@latest
```

As opposed to downloading a pre-built binary. Something like the above would be a useful addition to the README for installing `glow` as an alternative, or even replacement for, the `git clone ...; go build ...` sequence.

**Comment by taigrr** [comment]
I think this is closeable as of #308
