### ISSUE TITLE
Hyperlink highlighting continues to non-hyperlink texts when scrolling

### ISSUE THREAD

**Issue by bmitc** [charmbracelet/glow#365]
See the attached video for a demonstration. To reproduce:

1. Hover the mouse over a hyperlink such that the hyperlink changes color
2. Scroll the window using the arrow keys without moving the mouse
3. Notice that the hyperlink style gets applied to text in the same columns as the hyperlink

https://user-images.githubusercontent.com/65685447/183507277-35444e38-e021-4401-9de4-1397535058e8.mov

**Comment by muesli** [comment]
This looks like a bug in your terminal software and I'm not sure we can fix that. Which terminal is that?

**Comment by bmitc** [comment]
I was using [Warp](https://www.warp.dev/). I can create an issue in their repository and report back.

**Comment by meowgorithm** [comment]
Yeah, this is most likely a bug in the terminal emulator with regard to scrolling regions. For now you can probably set `GLOW_HIGH_PERFORMANCE_PAGER=false` in your environment to sidestep the issue.

**Comment by bmitc** [comment]
I filed an issue (https://github.com/warpdotdev/Warp/issues/1950) in the Warp repository, so I am going to close this one since there isn't any action items here. If it turns out it is a Charm/glow issue (sounds like not), this can always be re-opened.
