### ISSUE TITLE
install run error

### ISSUE THREAD

**Issue by 178me** [charmbracelet/glow#371]
archlinux 
The error occurred during installation
output: [1]    833445 segmentation fault  glow
Other computers can work normally

**Comment by muesli** [comment]
At which point is this segmentation fault occurring exactly? During installation of the package or on first run?

**Comment by 178me** [comment]
first run

**Comment by muesli** [comment]
Which CPU / architecture do you run this on? Which terminal are you using?

**Comment by caarlos0** [comment]
closing due to lack of response
