### ISSUE TITLE
Error: Open README.md: permission denied

### ISSUE THREAD

**Issue by markpendlebury** [charmbracelet/glow#372]
I've just installed glow in an attmept to read through a bunch of .md (in this case inside my `~/.oh-my-zsh/plugins/` directory.

If I simply type glow, it doesn't show any `.md` files, and if i try to open one directly i get: 

`Error: Open README.md: permission denied`

Screenshot showing result of `ls -la` and `glow README.md` 

![image](https://user-images.githubusercontent.com/63231900/187863259-621b877f-4c4c-4bac-830b-fcd1c12ee52e.png)

**Comment by markpendlebury** [comment]
I neglected to point out the above instance of glow was installed with `snap install glow` as we all know the would be a much better place without snaps... 

I've removed it and re-installed by adding your sources to my apt list and installing via apt as per your [readme](https://github.com/charmbracelet/glow#installation) fixes this issue

Issue can be closed but i thought i'd update incase anyone else stumbles across a similar issue

**Comment by muesli** [comment]
Snaps require specific confinements and access to a hidden directory in your home folder is prevented per default. Ubuntu is notorious about keeping these confinements rather strict (for better and worse), so there's probably nothing we can do about this one - sorry!
