### ISSUE TITLE
Ask: add glow to chocolatey

### ISSUE THREAD

**Issue by FallenGameR** [charmbracelet/glow#379]
In the Windows world Chocolatey package manager is one of the most popular ones.
Could the Glow authors add an official Chocolatey package for it?

**Comment by muesli** [comment]
You can find glow in chocolatey here: https://community.chocolatey.org/packages/glow

**Comment by muesli** [comment]
Added install instructions to README.

**Comment by FallenGameR** [comment]
Thank you! =)
