### ISSUE TITLE
So it is not a markdown reader yet?

### ISSUE THREAD

**Issue by AndyJado** [charmbracelet/glow#390]
Since I don't get to read a markdown file not seeing those markups.

So this is not a `markdown-reader-in-terminal` ?

**Comment by muesli** [comment]
It is. Which markups are you not seeing?

**Comment by AndyJado** [comment]
pardon my toes and tongue

by markups I mean `#` `url address` `*`, especially the url adress.

I don't think I should see them when I want to **read** a markdown file.

**Comment by muesli** [comment]
Can you post a screenshot of what's bothering you, I'm not sure I fully understand yet.

**Comment by AndyJado** [comment]
[this is proper markdown reading](https://github.com/charmbracelet/glow/issues/390)

```
[this is not a markdown reader](https://github.com/charmbracelet/glow/issues/390)
```

**Comment by muesli** [comment]
The issue is that not all terminals support OSC8 which allows for link markup. We're working on improving that situation however: https://github.com/muesli/termenv/commit/e706a87c011eba65893f94d6764974eec56bf223

**Comment by muesli** [comment]
Closing as dupe of #352.
