### ISSUE TITLE
no local files find under  /tmp

### ISSUE THREAD

**Issue by will1991** [charmbracelet/glow#423]
glow version: 1.14.1
ubuntu  20.04

glow can only working home directory. under Hidden directory,  also not find .md file. even use cmd : glow + file name, it not work well.
![image](https://user-images.githubusercontent.com/24243178/205414507-e380af42-315f-46f5-96a6-21292946e722.png)

**Comment by agarner-smart** [comment]
I may have the same (or similar?) issue. I have a hidden folder in my home directory which contains a `README.md` file, it is also a git repo. When I run `glow` with  no arguments I get no local files found, however I do get the file output when I run `glow README.md`. Not sure if this is expected? Glow seems to be working fine in other folders which are not hidden. I can't see any other differences causing this behaviour.

![Screenshot 2023-06-30 at 10 25 22](https://github.com/charmbracelet/glow/assets/116095666/8fcc9abc-50b2-4b51-b7f6-c694b5127bab)
![Screenshot 2023-06-30 at 10 25 46](https://github.com/charmbracelet/glow/assets/116095666/0dfd9e6d-de82-4d6d-9ec5-f62fe426bf9a)
![Screenshot 2023-06-30 at 10 28 50](https://github.com/charmbracelet/glow/assets/116095666/13fa52f1-dfc7-4d2d-aff6-bfcd513f5ee2)
 code folders.

**Comment by adriangalilea** [comment]
For me it doesn't work in `~` nor it works  in `~/notes` even when I specifically do `glow ~/notes` just sais no local files found, my home folder is also a git repo, just in case, with `.gitignore` content as `*`

**Comment by caarlos0** [comment]
seems to be fixed on master

**Comment by adriangalilea** [comment]
@caarlos0 not released on 1.5.1, right? Because it still doesn't work for me.

**Comment by caarlos0** [comment]
yeah, not released yet no


I'm going through all the issues, gonna try to jam as many as I can and then make a new release with many fixes
