### ISSUE TITLE
Automatically open README.md

### ISSUE THREAD

**Issue by oogali** [charmbracelet/glow#429]
As a prolific CLI spelunker, I would like `glow` when executed with no arguments, to open `README.md` if it exists in the current working directory.

Otherwise, send me to the home model (local/stashed/news).

(I would have tagged this with a feature request label if one was available)

**Comment by deicon** [comment]
How about defining an alias like this?

```bash
alias g="if [ -f Readme.md ]; then glow Readme.md; else glow; fi"
```
