### ISSUE TITLE
Won't Display Properly

### ISSUE THREAD

**Issue by abstractsins** [charmbracelet/glow#432]
I've used Glow on my previous machine and I enjoy it. I just installed on my new machine and it looks like this. Any idea why? Sorry if this is not the right place for this. 

![image](https://user-images.githubusercontent.com/18626012/209512400-b109f9ad-a9fc-4167-a090-ec48b1e04623.png)

**Comment by hyperreal64** [comment]
Hi, I had the same issue and found that it only happens when I use the pager feature and it was because I had the PAGER environment variable set. When I unset the PAGER environment variable, the glow pager displays properly. I'm using Linux, though. Do you have the PAGER set on your PowerShell instance by any chance?

**Comment by abstractsins** [comment]
Hi thanks for responding. No, I’m pretty sure I don’t.

**Comment by hyperreal64** [comment]
Hmm. On my Windows 11 PC, glow works fine in both Windows Terminal and Windows Console Host. Console Host is what you're using in the screenshot. However, I noticed you have an unusual prompt, `:^u`. How did you configure your prompt? I have a hunch that might have something to do with it.

**Comment by abstractsins** [comment]
I'm using windows 10 on my new machine.  The prompt is the same on my old windows 11 machines where it worked.  When using bash (pictured) it looks better but has no functionality. 
![image](https://user-images.githubusercontent.com/18626012/209603646-4ea65650-90b9-48e0-94d0-d93d454d6c8e.png)

**Comment by hyperreal64** [comment]
Ah I see. On the Bash instance, try running `unset PAGER`, and see if it works. I don't know if your Bash configuration sets the PAGER environment variable, though. If it's the default .bashrc, then it probably does.

**Comment by abstractsins** [comment]
oh i just went into options and unchecked "use legacy console" and now it works 
![image](https://user-images.githubusercontent.com/18626012/209603836-6fe313b6-939b-41e0-9e66-9b892b02a66d.png)

**Comment by hyperreal64** [comment]
I don't know how much you value your terminal experience, but I'd highly recommend [Windows Terminal](https://github.com/microsoft/terminal). :-)

**Comment by abstractsins** [comment]
Interesting, I'll give it a look, thanks
