### ISSUE TITLE
Force color output?

### ISSUE THREAD

**Issue by cwaldbieser** [charmbracelet/glow#440]
I'd like to use glow to preview markdown output in ranger-fm.  However, it seems that when the output is sent to a pipe or redirected to a file, all the ansi codes are stripped off.  This seems reasonable when you just want to save the output to a file or perform greps, etc.  However, is there some flag to force the ansi codes to be retained?

**Comment by cwaldbieser** [comment]
After poking around in the code, I noticed that if I explicitly set a style, it will be used regardless of whether or not we're writing to a terminal.  That works, but you lose the ability to detect light vs. dark style.

**Comment by Imericxu** [comment]
Setting `-s auto` worked for a bit but it just stopped working today and only the dark theme is being used (this is also for `ranger` btw).

**Comment by muesli** [comment]
`-s auto` is the default. You want to specify the actual theme, e.g. `-s dark`.

**Comment by Imericxu** [comment]
Omitting `-s` in `scope.sh` just disables all colors. And I don't want it to always be dark; I set up my terminal to sync with my device light/dark theme. I don't know if this is an issue with `ranger` or `glow`, but `bat` detects light and dark fine everywhere.

**Comment by varon** [comment]
Make sure that `COLORTERM` is defined in your env-vars and set to `truecolor`

**Comment by Anomalocaridid** [comment]
It seems like when using a custom theme, I need to specify the theme every time I want to force color output. The ability to force color output would be very helpful and save me from having to hardcode the path to my custom theme I want in things like shell scripts and aliases rather than just specifying it once in glow's config file.

**Comment by caarlos0** [comment]
you can force by setting `CLICOLOR_FORCE=1`, and in addition you might want to set `COLORTERM=truecolor` to have truecolor enabled as well.

**Comment by AndydeCleyre** [comment]
This seems to be new behavior since 2.0 I guess, whereas previously specifying a style was enough to ensure use of that style when piped. IMO it's worth a note on the GH release item.

**Comment by AndydeCleyre** [comment]
Although it's using a different (less readable) color scheme when piped, even though the color scheme (dark) is specified on the command line.

![image](https://github.com/user-attachments/assets/6eccf3ec-d66c-45aa-be1f-0e468aeae1d8)

**Comment by folliehiyuki** [comment]
> Although it's using a different (less readable) color scheme when piped

This is because when terminal output is not detected, and `CLICOLOR_FORCE=1` is set, `termenv` will use ANSI 4-bit color profile. See https://github.com/muesli/termenv/blob/82936c5ea257b458deb5238e6093773b42c43773/termenv.go#L104.

**Comment by AndydeCleyre** [comment]
Should it instead reuse the logic from https://github.com/muesli/termenv/blob/master/termenv_unix.go#L23 ? That checks `TERM` and `COLORTERM` as well as a list of known terminal emulators.

**Comment by mgnsk** [comment]
I've also had this issue for some time now. Since https://github.com/charmbracelet/glow/commit/1407793c5d11ceed9086c9779322617e633067a0, colors broke when glow is used as an fzf previewer.

Here's an example

Test file:
```markdown
# _Italic title_
```

Script:
```sh
#!/usr/bin/env bash

function preview {
	# broken since commit 1407793
	# before commit 1407793, I was using this command:
	# glow --style=auto "$1"

	# half-broken since commit 1407793, italic text but no color
	# glow --style=dark "$1"

	# almost works since 1407793 but wrong colors
	export CLICOLOR_FORCE=1
	export COLORTERM=truecolor
	glow --style=dark "$1"
}

export -f preview

fzf --preview "bash -c 'preview {}'"
```

How it looked before with `glow --style=auto "$1"`:
![okay](https://github.com/user-attachments/assets/7c30978a-b589-4c61-b5ac-9fe3d03cc8c9)

How it looks now with `CLICOLOR_FORCE=1 COLORTERM=truecolor glow --style=dark "$1"`:
![broken](https://github.com/user-attachments/assets/c2bbbc72-834f-4e10-ab04-c59aae698898)

**Comment by meowgorithm** [comment]
Oof, thanks for the heads up @AndydeCleyre and @mgnsk. This looks like a regression. Mind opening a PR accordingly?

**Comment by ostap-tymchenko** [comment]
Has anyone found any solutions? I'm trying to use glow for markdown editing via `watch -c -n 1 CLICOLOR_FORCE=1 glow DOC.md --style dracula` but I'm getting no luck. Just colorless output

**Comment by meowgorithm** [comment]
Just a note that we're chatting about the issue here: https://github.com/charmbracelet/glow/issues/654.

@caarlos0 just a note that it looks like `CLICOLOR_FORCE=1 COLORTERM=truecolor` no longer work together.
