### ISSUE TITLE
MINOR: glow --version tautology ("version version")

### ISSUE THREAD

**Issue by HenrikBengtsson** [charmbracelet/glow#445]
There's an extra "v(ersion)" after "version" in:

```sh
$ glow --version
glow version v1.5.0 (19732a6)
```

vs

```sh
$ glow --version
glow version 1.4.1 (4863f57)
```

**Comment by muesli** [comment]
Which package / distro are you using?

**Comment by HenrikBengtsson** [comment]
https://github.com/charmbracelet/glow/releases/download/v1.5.0/glow_1.5.0_Linux_x86_64.tar.gz

**Comment by caarlos0** [comment]
https://github.com/charmbracelet/meta/pull/68 should fix it
