### ISSUE TITLE
Inconsistent release names 

### ISSUE THREAD

**Issue by eggbean** [charmbracelet/glow#448]
Hi, really like glow, but as the apt repository doesn't seem to work very well and seems to have a lot of entries, I use a github action workflow instead, but now that keeps breaking too, as some of the release names have capitalised 'Linux' now and some do not. It's already pretty messy using both the RHEL-type architecture names (x86_64, aarch64) as well as Debian-type architecture names for other tarballs (amd64, arm64).

**Comment by caarlos0** [comment]
it doesnt even need the Linux word in the nfpm packages, as they are always for linux.

this should do the trick: https://github.com/charmbracelet/meta/pull/67

**Comment by eggbean** [comment]
Okay, thanks. Will see at the next release and hopefully they won't change again after that.
