### ISSUE TITLE
Auto-Complete Not Working

### ISSUE THREAD

**Issue by pendrini** [charmbracelet/glow#457]
The ability to tab autocomplete when opening files with glow has gone away recently. Wondering if anyone else has that issue.
- First noticed it when I upgraded to glow=1.5.0. 
- Removed glow and reinstalled. 
- Worked again for a moment, then gone again. 

Now I can't get anything to work. I'm on Pop_OS. Thank you.

**Comment by muesli** [comment]
Auto-completion is a feature of your shell, glow is not involved in this. I'd try and file an issue with popos / your shell.

**Comment by bewuethr** [comment]
But glow provides the shell completion script for tab completion, no, via `glow completion`? I have noticed a change as well, in that `glow <tab>` won't complete markdown files any longer, where earlier, it definitely did. Now, it just offers `completion`, `config`, `help`, and `stash`, but no files.

**Comment by pendrini** [comment]
I have reinstalled glow multiple times. Sometimes it works for a while, but it always stops working. sudo glow works. I have checked other packages with their autocomplete files in /etc/bash_completion.d and they all work in terms of bash autocomplete. I am out of ideas. I apologize if this is still a problem on my end. But it only started when I updated to 1.5.0. Any help would be great.

**Comment by tkapias** [comment]
The problem comes from the generated glow completion file in /etc/bash_completion.d/glow, when it's here the completion display some internal features put it break the path discovery.

Delete this file and never create it again, the current content of the completion script is useless.

**Comment by bewuethr** [comment]
@tkapias That fixed it for me. The PPA installation for glow puts it there, so that *does* like something to be fixed, either by not putting it there, or modifying such that it allows tab-completion of `.md` files and similar. I unfortunately don't know how Cobra and its tab completion generation works to be of more help here.

**Comment by tkapias** [comment]
I will try to write a simplier completion for bash and push a PR.

**Comment by pendrini** [comment]
@tkapias That fixed it for me too! Thank you so much for figuring this out. Happy that it got resolved.

**Comment by xcpky** [comment]
I am using fish, and this issue is not solved. there is no /etc/bash_completion.d/glow. But when I use bash, auto-complete works.

**Comment by mattcargile** [comment]
I have this issue on `glow completion powershell` too. Not sure how to handle or where the code lives in the repo.

**Comment by mattcargile** [comment]
Looks like the _issue_ would need to be opened [here](https://github.com/spf13/cobra)?

**Comment by mattcargile** [comment]
For `powershell`, the issue appears to be below and I am sure it is similar for others. It appears _cobra_ doesn't account for `command` + `<TAB>` to a file usage. They expect to tab into a sub command. Well for commands like `glow` this assumption doesn't work and we need to fall back to file completion.


https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/powershell_completions.go#L200-L211

**Comment by bewuethr** [comment]
> EDIT 1: So I think the key is the `ShellCompDirectiveNoFileComp` is in use so file completions aren't initiated.
> 
> If one does the below, it will shift to `ShellCompDirectiveDefault` which I assume will complete file paths then.
> 
> ```shell
> glow __complete "" 0
> ```
> 
> I'm going to try to open another Issue in the repo that controls this _Directive_.

According to the Cobra [shell completion doc](https://github.com/spf13/cobra/blob/main/shell_completions.md), it sounds like `ShellCompDirectiveFilterFileExt` with maybe `md` and `markdown` might work?

**Comment by mattcargile** [comment]
Ooo, that is awesome, @bewuethr ! I tried to recontextualize this "issue" as a feature here below. I have more info. I'll add the docs you just mentioned.

https://github.com/charmbracelet/glow/issues/512

**Comment by kranurag7** [comment]
> I am using fish, and this issue is not solved. there is no /etc/bash_completion.d/glow. But when I use bash, auto-complete works. 

I removed `~/.config/fish/completions/glow.fish` which I had before and it worked for me. If you're using `glow completion fish | source` in your `~/.config/fish/config.fish` file then consider removing that and it'll work in fish shell as well. 

// cc @xcpky
