### ISSUE TITLE
Unable to open file.md from GitHub that isn't README.md

### ISSUE THREAD

**Issue by jukremer** [charmbracelet/glow#464]
I tried opening a markdown [file](https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md) from a GitHub repo that isn't README.md.

`Error: can't find README in GitHub repository`

It doesn't open the README.md of that repo either, it just fails and provides this error message and the `help` page.

**Comment by caarlos0** [comment]
thanks, fixed, sorry for the delay
