### ISSUE TITLE
sorry for bothering

### ISSUE THREAD

**Issue by xp12047** [charmbracelet/glow#467]
How to change the default editor  
My computer is win11 and nano is not installed, can I switch to another editor? How to do it? Thanks  
![图片](https://user-images.githubusercontent.com/56335408/221101778-8089467b-a981-4b24-8fdd-908bf5e93dca.png)
config file on screenshot not working

**Comment by caarlos0** [comment]
Hi! It uses nano if the `EDITOR` environment variable is empty... if you set that env to `nvim` it should work.

**Comment by xp12047** [comment]
> Hi! It uses nano if the `EDITOR` environment variable is empty... if you set that env to `nvim` it should work.

Thank you very much it worked. At first I used powershell 7, maybe p7 didn't get it right. But I've been able to use the editor I specified on cmd, thank you very much
