### ISSUE TITLE
Force colors without forcing the style?

### ISSUE THREAD

**Issue by toonn** [charmbracelet/glow#474]
In ranger/ranger#2762 a user was trying to make use of Glow for Markdown previews and they didn't see any change so they assumed it didn't work.

Does Glow disable colors when run non-interactively, like ls does? Or is there a failing check for color capability maybe? What does Glow need to determine colors are OK to use?

**Comment by muesli** [comment]
Indeed, it disables styling when not attached to a terminal. Internally it uses `termenv` to detect the capabilities and settings of the terminal. You can enforce styling by either setting `CLICOLOR_FORCE` to `1` or passing a style manually, e.g. `glow -s dark`.

**Comment by toonn** [comment]
Would be nice if this was more obviously documented BTW. It seems Glow is missing a man page altogether?

**Comment by suchipi** [comment]
Fwiw, glow 1.5.0 on macOS doesn't seem to respect `CLICOLOR_FORCE=1`, but manually specifying a style does work.

**Comment by toonn** [comment]
@suchipi, I thought I'd noticed this regressing. Did it never work on macOS or is it really a regression in the behavior?

**Comment by suchipi** [comment]
Not sure; hadn't tried glow before yesterday

**Comment by toonn** [comment]
I know it worked at some point for me. Maybe it's because of a dependency?
@muesli, could you take a look at this?

**Comment by meowgorithm** [comment]
Just a note that we're discussing the issue here: https://github.com/charmbracelet/glow/issues/654
