### ISSUE TITLE
Respect XDG Base Directory specification on macOS

### ISSUE THREAD

**Issue by toonn** [charmbracelet/glow#475]
I was trying out Glow because of a user-reported issue on Ranger earlier and noticed that Glow defaults to writing configuration to `~/Library` on macOS.

While the Freedesktop [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) isn't really targeted at macOS, so many programs do respect the specification and make it a lot more convenient to manage configurations and such.

Could it be considered that Glow use the XDG Base Directories if the variables are defined in the environment and fall back to the usual location in `~/Library` otherwise?

Another minor note is that I was surprised Glow unconditionally writes a config file when running the `glow config` subcommand, even if no settings are changed. In general I prefer to configure only the things I specifically care about and fall back to defaults, which may change over time, determined to be best by upstream. Maybe the subcommand could check if any changes were made and only write the config if that was the case? And maybe it should offer all the possible settings commented out so you can set just the ones you care about and fall back to defaults for everything else?

**Comment by 5ouma** [comment]
I'm so agree with this Issue!
I want to set the same config file on macOS and Linux with the same `~/.config/glow/glow.yml`.

**Comment by meowgorithm** [comment]
This is now in `master` and will be available in the next release. Thanks for flagging this, it was bugging me too!
