### ISSUE TITLE
[feature] Command key / file alteration in glow interface to reload the file

### ISSUE THREAD

**Issue by erikh** [charmbracelet/glow#481]
#480 was my earlier ticket, I discovered that just by typing `glow` I could get a much richer UI with a pager (that even word wraps properly!) so I'm using that for now, even though I would still like the feature described in that ticket.

I would also like a hot key in the built-in pager interface to reload the file. A workflow I've found handy is to use tmux, split vertically, and start glow on one side and vim on the other, which is nice to see my edits. Right now, it's not a huge deal, but I have to hit escape, enter, to see my edits.

What would be nice is a "reload" key, or if you're feeling fancy, reloading automatically on file write through use of file alteration APIs, so I can see my edits appear immediately.

**Comment by caarlos0** [comment]
you should be able to press `r` to reload the document (on master).


thanks for the issue, sorry about the delay! Cheers!
