### ISSUE TITLE
vim codeblock renders with red boxes at end of each line

### ISSUE THREAD

**Issue by kaddkaka** [charmbracelet/glow#485]
````console
$ cat xdg_vim.md
```vim
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath^=$XDG_CONFIG_HOME/vim
```

```
set runtimepath^=$XDG_CONFIG_HOME/vim
```
````

Renders as:
![image](https://user-images.githubusercontent.com/4508793/231263750-c748a471-d758-46b1-9c3f-476fe83096c8.png)

```console
$ glow xdg_vim.md


    set runtimepath^=$XDG_CONFIG_HOME/vim
    set runtimepath^=$XDG_CONFIG_HOME/vim

    set runtimepath^=$XDG_CONFIG_HOME/vim
```

Is this expected? Is there something incorrect with the vim source in the markdown file?

`glow version v1.5.0 (19732a6)`

**Comment by PratikBhusal** [comment]
> Is this expected? Is there something incorrect with the vim source in the markdown file?

This may not be exactly what you are after, but I was able to fix the vim-specific glow issue in my branch:

https://github.com/PratikBhusal/glow

Here's a screenshot of it as proof:

![2024-02-18-22_51_28](https://github.com/charmbracelet/glow/assets/20880924/89ddbbe9-9e38-48a7-9402-98b3ccbbb9f8)

I have a PR up to fix it within the glamour renderer. Once that is merged I can get it fixed within glow as well.

See:

- https://github.com/charmbracelet/glamour/pull/282
