### ISSUE TITLE
Support `GLOW_CONFIG_DIR` env var

### ISSUE THREAD

**Issue by cristiand391** [charmbracelet/glow#495]
hi 👋🏼 

I'm trying to consolidate my dotfiles to be the same on macos and linux and have a small issue with how glow handles its config file.

I have a script that runs `yq --inplace '.style = "dark"' ~/.config/glow/glow.yml` when switching between dark/light in my OS to set the right theme for glow but can't reuse the same script on mac and linux  because on mac the path is `~/Library/Preferences/glow/glow.yml` vs `~/.config/glow/glow.yml` on linux.
[I saw this issue requesting to support XDG paths](https://github.com/charmbracelet/glow/issues/328) and then found that glow uses `go-app-paths` to handle platform-specific paths so this should be fixed/added there to work on mac (XDG is supported on linux).

This feature request is to allow users to specify a path for the config file via an env var like `GLOW_CONFIG_DIR`.
It wouldn't be a breaking change like adding support for XDG  on macos and seems easy to add (happy to open a PR  if you'll agree on this request :) )

**Comment by Subjective** [comment]
I second this, as it stands currently glow's config is the only remaining config I have in the ~/Library/Preferences folder. It be great if we could have the option to customize the path  :)

**Comment by ptrck0** [comment]
Made a [PR](https://github.com/charmbracelet/glow/pull/594) to implement this.
