### ISSUE TITLE
[feature] Supertxt file highlighting

### ISSUE THREAD

**Issue by supertxtnet** [charmbracelet/glow#498]
[Supertxt](https://supertxt.net) is another lightweight markup language like markdown, and [gemtext](https://gemini.circumlunar.space/docs/gemtext.gmi). If the file extension of the path is ".s.txt" then it would be really helpful to get the syntax highlighting for it. Perhaps the same can be done for gemtext too if it is ".gmi."

There's a [Go library](https://pkg.go.dev/supertxt.net/git/st-int@v0.1.1/parse) for lexing SuperTXT, and a [specification](https://supertxt.net/specs/supertxt.html).

**Comment by gedw99** [comment]
This looks really interesting @supertxtnet

**Comment by caarlos0** [comment]
I think we're going to focus on markdown for now.

thanks for the suggestion and sorry for the delay
