### ISSUE TITLE
feature: render ~~strikethrough~~

### ISSUE THREAD

**Issue by crides** [charmbracelet/glow#510]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add ~~strikethrough~~ rendering with `~~strikethrough~~`. Apparently on Discord it's `~~` but GFM speced it to be `~` or `~~`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bashbunni** [comment]
Related:
https://github.com/yuin/goldmark/blob/master/extension/ast/strikethrough.go
[looks like Terminal.app doesn't support strikethrough text](https://en.wikipedia.org/wiki/ANSI_escape_code)

**Comment by snoweuph** [comment]
```bash
printf "\e[9m"
printf "Some Text"
printf "\e[m\n"
```

works for me in bash, with:
- Konsole
- Alacritty
- Kitty
- BlackBox
- Gnome Terminal

**Comment by caarlos0** [comment]
this is fixed on master
