### ISSUE TITLE
Path AutoComplete On First Argument

### ISSUE THREAD

**Issue by mattcargile** [charmbracelet/glow#512]
**Is your feature request related to a problem? Please describe.**
It would be nice to see the autocomplete script use the `ShellCompDirectiveDefault` instead of `ShellCompDirectiveNoFileComp`  on completion of the first argument. It appears that is the default too.

~~It appears like it could be completed with [this](https://github.com/spf13/cobra/blob/284f4101043c4b1faebde411caec35a7b6e36494/active_help.md#adding-active-help-melssages) `ValidArgsFunction`.~~ I think it can be handled with [this](https://github.com/spf13/cobra/blob/main/site/content/completions/_index.md) doc. And ideally maybe `ShellCompDirectiveFilterFileExt` for `.md` files or `.markdown` files. 

I assume the edit would be somewhere here.

https://github.com/charmbracelet/glow/blob/58ec3516920d9cf054ce12f8e07b80611dba3b72/main.go#L40-L48

I'm not exactly sure how it works but `oh-my-posh` is able to do some of it below. For instance, `oh-my-posh.exe print --config ` + `<TAB>` will complete a path. The code being executed is `oh-my-posh.exe __complete print --config ""` to get the path which will show `ShellDirectiveDefault`.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/a0742d640b21d3ffca5af1a4910fe4e329c558ec/src/cli/print.go#L29-L91

**Describe the solution you'd like**
I would like paths and the sub commands to be auto completed.

**Describe alternatives you've considered**
Right now, I have the completion turned off as it isn't useful without the path completion. Typical usage is `glow` + `<TAB>` into a file.

**Additional context**
Additional context added above.

**Comment by tmzhuang** [comment]
This seems to be still broken for me on bash. Running `glow completion bash > ~/scripts/glow_completion.sh` and then sourcing the file does not seem to resolve the issue. Pressing tab gives the behavior described in the initial comment.

**Comment by caarlos0** [comment]
are you using glow from master? I think the fix is not yet released...

**Comment by mattcargile** [comment]
Speaking of _release_ . Are we getting one anytime soon, @caarlos0 ?

Side note, this issue should probably be closed too.
https://github.com/charmbracelet/glow/issues/536

**Comment by caarlos0** [comment]
Yes! I think next week! Please do test the master branch if you can, though 🙏

**Comment by mattcargile** [comment]
> Yes! I think next week! Please do test the master branch if you can, though 🙏

Just built it. Tab works great now on paths. 👍🏻
