### ISSUE TITLE
Syntax highlighting colours don't match given colours 

### ISSUE THREAD

**Issue by randomcoder67** [charmbracelet/glow#517]
**Describe the bug**
Colours don't match with what they are set to in theme file. 

**Setup**
 - OS: Arch
 - Shell : Bash
 - Terminal Emulator: Alacritty (testing in Xfce4 Terminal as well, same issue)
 - Terminal Multiplexer: N/A
 - Locale: en_GB.UTF-8

**To Reproduce**
I noticed this when trying to change syntax highlighting colours. I set strings to the same hex value as my terminals yellow colour, but the colours don't match in the terminal. This can be verified by zooming in to negate the anti-aliasing then screenshot and use the GIMP colour picker. 

The terminal yellow colour is set to `#ffc66d`, and this displays correctly in neofetch. But in glow, it appears as `#ffd75f`, noticeably "brighter". 
This doesn't just happen with yellow it's just the most noticeable in my theme. 

**Source Code**
```
"literal_string": {
				"color": "#ffc66d"
			},
```

**Expected behavior**
The colours matching up

**Screenshots**
![saved2](https://github.com/charmbracelet/glow/assets/135234789/0c0071bf-2124-4338-bbf8-1b579537d9fc)

**Comment by stucash** [comment]
Same issue here on Xfce4 terminal, my style sheet simply doesn't work. Dark theme gives me two random colours and that's all. I am on a variant of Debian 11 stable (bullseye).

```
> tput color
256
> echo $TERM
xterm-256color
```

**Comment by caarlos0** [comment]
I think this should be fixed on master... glow was not using the same profile in glamour for some reason, which should be fixed now.
