### ISSUE TITLE
The first few lines are not shown in dracula theme

### ISSUE THREAD

**Issue by Urie96** [charmbracelet/glow#522]
**Setup**
Please complete the following information along with version numbers, if applicable.
 - macOS
 - fish
 - alacritty

1. create file `test.md`
2. Write many lines so that one page cannot display all
3. run `glow test.md -p -s dracula`
4. the first line are not shown and unable to scroll up (everything works good in default theme)

**Comment by caarlos0** [comment]
cannot repro on master
