### ISSUE TITLE
install error on go 1.13.8

### ISSUE THREAD

**Issue by amagnasco** [charmbracelet/glow#523]
On cloning into repo and running go build, receive the following error:
build github.com/charmbracelet/glow: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element

**Setup**
Please complete the following information along with version numbers, if applicable.
 - Ubuntu Studio 
 - Zsh on Guake
 - go version go1.13.8 linux/amd64

**To Reproduce**
1. clone the repo and cd in
2. go build

**Comment by bashbunni** [comment]
Hey @amagnasco in our `go.mod` we declare the minimum version of Go for the module to be version `1.17`. We can't guarantee that the module will work in versions prior to `1.17`. I hope that helps :)

https://go.dev/ref/mod#go-mod-file-go
