### ISSUE TITLE
URLs are stripped out of table cells

### ISSUE THREAD

**Issue by AjBreidenbach** [charmbracelet/glow#525]
**Describe the bug**
Text that would normally be formatted as a URL is not rendered at all within table cells.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS Ubuntu 20.04.6 LTS
 - Shell bash, fish
 - Terminal Emulator alacritty, gnome terminal
 - Terminal Multiplexer N/A
 - Locale en_US.UTF-8
 - Glow version 1.5.1

**To Reproduce**
Use glow to render any table where a cell contains a URL:

```
| ID | Description                     | Tags     | Priority | Status      |
|----|---------------------------------|----------|----------|-------------|
| 50 | <https://scribblediffusion.com> | question | 5        | Not started |
```
Renders to:
```
    ID │ DESCRIPTION │   TAGS   │ PRIORITY │   STATUS
  ─────┼─────────────┼──────────┼──────────┼──────────────
    50 │             │ question │        5 │ Not started
```

**Expected behavior**
The URL or at least plain text to be rendered in the table cell

**Comment by bashbunni** [comment]
This is fixed in the upstream Glamour dependency. The next release of Glamour will fix this in Glow :)
