### ISSUE TITLE
How do I change glow default nano to vim? 

### ISSUE THREAD

**Issue by aharoJ** [charmbracelet/glow#526]
Anyone please, I looked over the docs and the config and I cant seem to find the way to change it.

**Comment by jaymorelli96** [comment]
I think it will default to your `$EDITOR` env. Make sure it is set to your favorite editor 😄

**Comment by bashbunni** [comment]
@jaymorelli96 is right! It will look for your `$EDITOR` environment variable. 
https://github.com/charmbracelet/glow/blob/f0734709f0be19a34e648caaf63340938a50caa2/editor/editor.go#L11

Here's how you can set these variables:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3

On Mac or Linux, you can include a line like `export EDITOR="vim"` in your `~/.zshrc` or `~/.bashrc`

**Comment by p6002** [comment]
And what should I do if `$EDITOR` is set to micro, and glow still opens in nano?

**Comment by bashbunni** [comment]
@p6002 is micro in your `PATH`? How are you setting the `EDITOR` environment variable?
