### ISSUE TITLE
No path completion on zsh 5.9

### ISSUE THREAD

**Issue by wintermute-cell** [charmbracelet/glow#533]
**Describe the bug**
There is no path completion when using `glow <tab>` on zsh.

I have (hopefully correctly) set up the completion file:
```bash
glow completion zsh > ~/.config/zsh/completion_files/_glow
echo "fpath=(~/.config/zsh/completion_files $fpath) >> ~/.zshrc
```

**Setup**
```bash
~ % zsh --version
zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
~ % glow --version
glow --version
glow version 1.5.1 (ad21129)
```

**Comment by Laura7089** [comment]
I'm also having this problem:
```
zsh 5.9
glow version 1.5.1 (ad21129
```

**Comment by mattcargile** [comment]
Probably related to the _cobra_ config in there source. See below.
https://github.com/charmbracelet/glow/issues/512
