### ISSUE TITLE
Tab path completion doesn't work when I use glow to open a file in another directory

### ISSUE THREAD

**Issue by JaoCN** [charmbracelet/glow#536]
**Describe the bug**

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS [Ubuntu16.04]
 - Shell [bash]
 - Locale [e.g. en_US.UTF-8,]

**To Reproduce**

now I'm in the `/path1` directory and I want to open the `/path1/path2/README.md` file, when I type `glow path2` and press TAB to complete the path, the TAB command doesn't work!

**Source Code**
Please include source code if needed to reproduce the behavior. 

**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Additional context**

**Comment by JaoCN** [comment]
but when I type `glow stash path2` and press TAB, it works.

**Comment by nightshade427** [comment]
same here

**Comment by mattcargile** [comment]
Probably related to my issue here. It is config for `cobra`.
https://github.com/charmbracelet/glow/issues/512

**Comment by mattcargile** [comment]
This may be closed by this commit.
https://github.com/charmbracelet/glow/commit/d7032fe57f7aa06e3e8f04f810db6796ed8fe42d

**Comment by heaths** [comment]
Is another release planned anytime soon including this change? It's been over a year since the last release was published to GitHub, at least, which is the same version as the latest in homebrew currently.

**Comment by caarlos0** [comment]
Should be fixed on master

**Comment by heaths** [comment]
I appreciate that, but for those of us using package managers e.g., homebrew, new binaries haven't been released in over a year:

![image](https://github.com/user-attachments/assets/36f59b31-1ea5-478f-b217-0d6f55579b9d)

Are binary releases no longer recommended? Should we just `go install` glow?

**Comment by caarlos0** [comment]
we're planning on releasing next week!
