### ISSUE TITLE
Colorize text inside a table  

### ISSUE THREAD

**Issue by R0nBC** [charmbracelet/glow#544]
I find text in colors inside a table a very basic feature for this utility. 
Glow can read html tags but when displaying the file via glow cli, the colors are not seen.  
Example: 
This is the file: 
<style>
.colored-text {
  color: red;
}
</style>

| Fruit | Color |
|---|---|
| Apple | <span style="color:red">Red</span> |
| Orange | <span class="colored-text">Orange</span> |
| Banana | <span class="colored-text">Yellow</span> |
| Grape | <span class="colored-text">Purple</span> |

**This is the output:** 
./glow table.html
    FRUIT  │ COLOR
  ─────────┼─────────
    Apple  │ Red
    Orange │ Orange
    Banana │ Yellow
    Grape  │ Purple

**Comment by R0nBC** [comment]
What I'm actually asking is if there is a way to display colors inside table via glow?

**Comment by caarlos0** [comment]
I don't think its possible right now... will leave it here to investigate

**Comment by caarlos0** [comment]
also, duplicated of #529
