### ISSUE TITLE
Table formatting breaks if output is piped

### ISSUE THREAD

**Issue by patrislav1** [charmbracelet/glow#545]
**Describe the bug**

Table formatting breaks when stdout is piped to a file or a program. `glow` seems to detect if stdout is connected to a tty, and leaves out some table formatting if it's not.

I would like to pipe `glow` output to tools like `grep` and `fzf` and still have the correct table formatting.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS [e.g. Ubuntu, macOS]: Ubuntu 22.04
 - Shell [e.g. zsh, fish]: zsh
 - Terminal Emulator [e.g. kitty, iterm]: kitty
 - Terminal Multiplexer [e.g. tmux]: Bug reproduces both with and without tmux
 - Locale [e.g. en_US.UTF-8, zh_CN.UTF-8, etc.]: en_US.UTF-8

**To Reproduce**

```
$ glow test.md                                     

                                                                                                                    
    FIRST COLUMN │ SECOND COLUMN                                                                                      
  ───────────────┼────────────────                                                                                    
    Foo          │ Bar                                                                                                
                 │ Baz                                                                                                

$ glow test.md | cat                               


FIRST COLUMN │ SECOND COLUMN
───────────────┼────────────────
Foo          │ Bar
│ Baz

$ socat - EXEC:'glow test.md',pty,setsid,ctty | cat

                                                                            
    FIRST COLUMN │ SECOND COLUMN                                              
  ───────────────┼────────────────                                            
    Foo          │ Bar                                                        
                 │ Baz                                                        

```

**Source Code**
Please include source code if needed to reproduce the behavior. 
```md
| First column | Second column |
|--------------|---------------|
| Foo          | Bar           |
|              | Baz           |
```

**Expected behavior**
Table formatting should be maintained regardless of TTY presence.

**Screenshots**
![image](https://github.com/charmbracelet/glow/assets/17723608/73d4a30a-364f-4d6a-bec7-e7d37fd3b96c)

**Additional context**
N/A

**Comment by patrislav1** [comment]
PS.: After reading [main.go](https://github.com/charmbracelet/glow/blob/c991ec475d777f9656b29fd861ff4b38f5d8313c/main.go#L156C24-L156C24) it turns out that this bug can be mitigated with explicit style option (e.g. `-s dark`)

**Comment by caarlos0** [comment]
yeah, I think this is on purpose since the output is not a TTY...

imho not a bug.

**Comment by patrislav1** [comment]
If output like this is as expected, what would be the use case? (Genuine question). OTOH, what use case would break if the tables were correctly formatted even when not directly output to a TTY?

```
FIRST COLUMN │ SECOND COLUMN
───────────────┼────────────────
Foo          │ Bar
│ Baz
```
