### ISSUE TITLE
Tab completion f/glow

### ISSUE THREAD

**Issue by iconoclasthero** [charmbracelet/glow#546]
**Is your feature request related to a problem? Please describe.**
No tab completion in bash for the readme files from git packages.

**Describe the solution you'd like**
BASH (and I'm not opposed to other shells too!) tab completion for whatever files this is designed to view, but **absolutely README.md files that you generate on git!!!!**

**Describe alternatives you've considered**
Done: `alias glowr='glow README.md'`
Been meaning to do for a long time: Actually implement tab completion for this myself, but then a) I'd have to look it up and b) it wouldn't help anyone else.

**Additional context**
can't think of any.

**Comment by mattcargile** [comment]
It could be related to my issue here.
https://github.com/charmbracelet/glow/issues/512
