### ISSUE TITLE
Open Editors at Current Line Number in Pager

### ISSUE THREAD

**Issue by h0rv** [charmbracelet/glow#547]
**Is your feature request related to a problem? Please describe.**

I am currently working on https://github.com/charmbracelet/glow/issues/535, and I think it would be a really neat workflow to 1. Open file with glow with `-e` flag, and edit the file and hop back and forth with the editor quickly and seamlessly.

**Describe the solution you'd like**

I use NeoVim, so for vim-like editors, we can pass in the current line information when opening the editor like so: `vi +25 README.md` to open the file at line 25. 

We would need to check if the editor is Vi/Vim/NeoVim before passing the flag.

We can potentially add support for more editors if they support such a feature.

**Describe alternatives you've considered**

This is potentially not possible if the pager does not have the ability to get the current line number, but I think that is unlikely.

**Comment by h0rv** [comment]
Looks like nano all supports `+<file number>` flag

**Comment by 4l1fe** [comment]
Kakoune allows to set the line as well `kak +3192:5 config.yml`
