### ISSUE TITLE
`rst` Support

### ISSUE THREAD

**Issue by brian6932** [charmbracelet/glow#561]
**Is your feature request related to a problem? Please describe.**
ReStructured Text's kinda like Markdown, and with this GH issue being a thing https://github.com/orgs/community/discussions/86715. It's a better time than any to add support.

**Describe the solution you'd like**
An `rst` mode, prob with a flag and file extension check, shouldn't be default ofc.

**Describe alternatives you've considered**
Opening `rst` files in glow currently renders them as Markdown, which's kinda close, but doesn't entirely work.

**Comment by caarlos0** [comment]
I think we're going to focus on markdown for now.

thanks for the suggestion and sorry for the delay
