### ISSUE TITLE
level 2, 3, etc headers do not get rendered

### ISSUE THREAD

**Issue by thisismygitrepo** [charmbracelet/glow#583]
# This header is rendered.

##not this

###Nor this

etc

**Comment by bashbunni** [comment]
Hey, it looks like your formatting might be off. Are you still having this issue if you add a space between the "#" and the heading text? Please let us know if that's the case :)

**Comment by thisismygitrepo** [comment]
Hi @bashbunni 

I deliberately did that misformating to mimic how `glow` fails to render.

The actual failure occurs even when you do the correct formatting with spaces you mentioned.

This is what I'm getting now:

![image](https://github.com/charmbracelet/glow/assets/46288868/7dca4ab3-188f-4448-9055-69af6cdc3f87)

**Comment by thisismygitrepo** [comment]
Looking at the GIF in the read me, it shows similar results to what I get, so apparently this is not a bug, its just how glow renders.

https://github.com/charmbracelet/glow?tab=readme-ov-file

Hmmm, keeping the hash as is is not very esthetic imo

**Comment by bashbunni** [comment]
Hey @thisismygitrepo you can set your own custom styles for Glamour (the markdown renderer itself) that will then be used in Glow.

To use custom styles in Glamour, you can create your own style config file. In this case, I would recommend finding the `json` file of the theme that you like most, then tweaking it to your own preferences. For example, with this dark theme, you can remove the prefixes for the headings, then use the `-s` flag to pass your own custom stylesheet. Your question also made me realize that we're missing support for defining custom styles with environment variables (`GLAMOUR_STYLE`) in Glow, so I've opened [a PR](https://github.com/charmbracelet/glow/pull/587) to that effect.
https://github.com/charmbracelet/glamour/blob/master/styles/dark.json

[Where to find this info in the docs](https://github.com/charmbracelet/glow?tab=readme-ov-file#styles)

I hope that helps! Let me know if there's anything I missed in your question :)
