### ISSUE TITLE
Print specific part of the Markdown by syntax 

### ISSUE THREAD

**Issue by marcelarie** [charmbracelet/glow#605]
I've been using glow for a while now, and thought of a few cool features that could make it even better. Not sure if these fit the project's direction, but here they are:

1. **Selective Header Printing**: It'd be awesome to print specific headers directly. Something like:
   
```shell
glow --elements=header --patter-=User*
```
   to get all element headers starting with "User".
   
  The elements could be:

- heading
- code_block
- list
- link
- image
- blockquote
- table
- hr
- code
- emphasis
- task_list
- footnote
- math
- definition_list
- html

Another useful example would be to print only code blocks:
   
```shell
glow --elements=code_block
```

These ideas might be a bit scattered, but in a way I think are related. 

2. **Viewing Specific Document Sections**: Like `tail` or `head`. Quick examples:
   - For the first 10 lines:
     
```shell
glow --head
```
   - For the last 10 lines:
     
```shell
glow --tail=10
```
   - For the first 5 lines:
     
```shell
glow --head=5
```

   If it's tricky to implement, maybe a `--color-always` option could help keep syntax color when piping to `head` or `tail`.

**Comment by caarlos0** [comment]
hey, I don't think this is within the scope of glow, at least not now.

thanks for the issue though, and sorry for the delay!
