### ISSUE TITLE
Source/Dir argument doesn't handle escape characters

### ISSUE THREAD

**Issue by kylernocturnalnerd** [charmbracelet/glow#620]
when providing an argument like:
/home/user/a\ personal\ markdown\ file.md

it says it cannot find a file:
`glow /home/krobinson/Documents/Second\ Brain/Knowledge/Linux/LVM/LVM.md`
results in:
`Error: open Brain/Knowledge/Linux/LVM/LVM.md: no such file or directory`

Reproduce:
nix run nixpkgs#glow -- mdfilewitha\ spaceinthepath.md

 - OS: nixos
 - Shell: zsh
 - Terminal Emulator: konsole
 - Terminal Multiplexer N/A
 - Locale en_US.UTF-8
 - Version: 1.5.1

**Comment by caarlos0** [comment]
these escapes are handled by the shell, not by glow...

either way, tested here, seems to work fine.
