### ISSUE TITLE
usage of glow to edit/write markdown file as well

### ISSUE THREAD

**Issue by 0verread** [charmbracelet/glow#628]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
glow renders markdown file content in a beautiful way on the terminal. I would love to use it to edit my markdown file as well. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by caarlos0** [comment]
you can press `e` to open the default editor. 🙏
