### ISSUE TITLE
Make build work offline

### ISSUE THREAD

**Issue by ottok** [charmbracelet/glow#660]
While packaging Glow for Debian, I noticed that the build fails as it is not designed to be able to run offline.

The Debian builds run in a hermetic environment that has no external
access neither in nor out. This ensures high level of reproducibility,
stability and security. Glow should refactor these tests so that they
only run if the build is called with some special debug/test tag, or
have a pre-test that skips the tests automatically if there is no network
connection at all.

Thanks!

**Comment by bashbunni** [comment]
Hey, thanks for bringing this to our attention. I've just created a PR to address this
